import {test,expect} from '@playwright/test';
test('audit pagination, server filters, redaction and facility scope',async({page})=>{
 const r=page.request;await r.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}});
 const p=await (await r.post('/api/patients',{data:{age:40,language:'en',consent:true}})).json();
 const e=await (await r.post('/api/encounters',{data:{patientId:p.data.id,text:'Patient reports fever.',language:'en',inputType:'text'}})).json(),id=e.data.id;
 await r.post('/api/triage/analyze',{data:{encounterId:id}});await r.post('/api/reviews/workspace',{data:{username:'doctor.ananya',password:'Doctor!2026'}});
 await r.post('/api/reviews/override',{data:{encounterId:id,newPriority:'RED',reason:'Original concerns need qualified review.'}});
 const ids=new Set<string>();let cursor='';let pages=0;
 do{const response=await r.get(`/api/audit?limit=2&q=${id}${cursor?'&cursor='+cursor:''}`);expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toContain('no-store');const value=await response.json();expect(value.data.length).toBeLessThanOrEqual(2);for(const event of value.data){expect(ids.has(event.id)).toBe(false);ids.add(event.id);expect(event.encounterId).toBe(id);expect(event.metadata.reason).toBeUndefined();}cursor=response.headers()['x-next-cursor']??'';pages++;expect(pages).toBeLessThan(30);}while(cursor);
 expect(pages).toBeGreaterThan(1);
 const hidden=await (await r.get(`/api/audit?q=${id}&hideAccess=true`)).json();expect(hidden.data.some((e:{action:string})=>e.action==='CASE_ACCESS_AUTHORIZED')).toBe(false);
 const readable=await (await r.get(`/api/audit/${id}?q=risk%20override`)).json();expect(readable.data.length).toBe(1);expect(readable.data[0].action).toBe('RISK_OVERRIDE');expect(readable.data[0].metadata.reason).toBe('Original concerns need qualified review.');
 const named=await (await r.get(`/api/audit/${id}?q=Ananya`)).json();expect(named.data.length).toBeGreaterThan(0);expect(named.data.every((event:{actorName:string})=>event.actorName==='Dr. Ananya Rao')).toBe(true);
 expect((await r.get('/api/audit?cursor=invalid')).status()).toBe(400);expect((await r.get('/api/audit?limit=10000')).status()).toBe(400);
 expect((await r.get('/api/audit?from=2026-10-13T00:00:00%2B05:30&to=2026-10-02T00:00:00%2B05:30')).status()).toBe(400);
 expect((await r.get('/api/audit?from=not-a-date')).status()).toBe(400);
 await page.goto('/audit');await page.getByLabel('Filter events').fill(id);await page.getByRole('button',{name:'Apply audit filters'}).click();await expect(page.locator('tbody')).toContainText('RISK_OVERRIDE');
 await r.post('/api/auth/credentials',{data:{username:'receiver.scb',password:'ReceiverTestOnly!2026'}});expect((await r.get(`/api/audit/${id}`)).status()).toBe(404);expect((await (await r.get(`/api/audit?q=${id}`)).json()).data).toEqual([]);
});

test('case audit keeps priority visible through filtering and refreshes clinical changes',async({page})=>{
 const r=page.request;
 expect((await r.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}})).status()).toBe(200);
 const patient=await (await r.post('/api/patients',{data:{age:45,language:'en',consent:true}})).json();
 const encounter=await (await r.post('/api/encounters',{data:{patientId:patient.data.id,text:'I have difficulty breathing.',language:'en',inputType:'text'}})).json(),id=encounter.data.id;
 expect((await r.post('/api/triage/analyze',{data:{encounterId:id}})).status()).toBe(200);
 await r.post('/api/reviews/workspace',{data:{username:'doctor.ananya',password:'Doctor!2026'}});
 await page.goto(`/audit?encounterId=${id}`);
 const summary=page.locator('section').filter({has:page.getByRole('heading',{name:'Case priority and referral'})});
 await expect(summary).toContainText('RED');
 await page.getByLabel('Hide routine access events in this view').check();
 await page.getByRole('button',{name:'Apply audit filters'}).click();
 await expect(page.getByRole('button',{name:'Refresh audit'})).toBeEnabled();
 await expect(summary).toContainText('RED');
 await expect(page.locator('tbody')).toContainText('TRIAGE_COMPLETED');
 await expect(page.locator('tbody')).not.toContainText('CASE_ACCESS_AUTHORIZED');
 await page.getByLabel('From date (IST)').fill('1970-01-01');await page.getByLabel('To date (IST)').fill('1970-01-02');
 await page.getByRole('button',{name:'Apply audit filters'}).click();
 await expect(page.getByText('No audit events match these filters.')).toBeVisible();await expect(summary).toContainText('RED');
 await page.getByLabel('From date (IST)').fill('1970-01-03');await page.getByRole('button',{name:'Apply audit filters'}).click();
 await expect(page.locator('p[role=alert]')).toContainText('From date must be on or before to date.');
 await page.getByRole('button',{name:'Reset filters'}).click();await expect(page.locator('tbody')).toContainText('TRIAGE_COMPLETED');await expect(summary).toContainText('RED');
 const reason='Source reviewed by the authorized doctor for this test.';
 expect((await r.post('/api/reviews/override',{data:{encounterId:id,newPriority:'YELLOW',reason}})).status()).toBe(200);
 expect((await r.post('/api/reviews',{data:{encounterId:id,decision:'APPROVE'}})).status()).toBe(200);
 await page.getByRole('button',{name:'Refresh audit'}).click();await expect(summary).toContainText('YELLOW');await expect(summary).toContainText('APPROVED');
 await expect(summary.getByRole('link',{name:'Review risk and refer'})).toHaveAttribute('href',`/referrals?case=${id}`);
 await page.getByLabel('Filter events').fill('risk override');await page.getByRole('button',{name:'Apply audit filters'}).click();
 await expect(page.locator('tbody tr')).toHaveCount(1);await page.getByText('Event details',{exact:true}).click();await expect(page.locator('tbody')).toContainText(reason);
 await r.delete('/api/reviews/workspace');await page.getByRole('button',{name:'Refresh audit'}).click();await expect(page.locator('tbody')).not.toContainText(reason);
 await page.getByRole('link',{name:'View facility audit'}).click();await expect(page.getByRole('heading',{name:'Facility activity'})).toBeVisible();await expect(page.getByLabel('Filter events')).toHaveValue('');
 await page.getByRole('link',{name:id,exact:true}).first().click();await expect(summary).toContainText('APPROVED');await expect(page.getByLabel('Filter events')).toHaveValue('');
 await page.getByRole('button',{name:'Reset filters'}).click();
 expect((await r.post('/api/privacy/consent',{data:{patientId:patient.data.id,withdraw:true,requestConfirmed:true}})).status()).toBe(200);
 await page.getByRole('button',{name:'Refresh audit'}).click();await expect(page.locator('p[role=alert]')).toContainText('Consented case audit unavailable.');
 await expect(summary).toHaveCount(0);await expect(page.locator('tbody tr')).toHaveCount(0);
 await r.post('/api/auth/credentials',{data:{username:'administrator',password:'Admin!2026'}});
 const governance=await (await r.get(`/api/audit/${id}`)).json();expect(governance.ok).toBe(true);expect(governance.case).toBeNull();expect(governance.data.length).toBeGreaterThan(0);expect(governance.data.every((event:{metadata:Record<string,unknown>})=>event.metadata.reason===undefined)).toBe(true);
});

test('audit paging survives a failed request and session expiry clears protected content',async({page})=>{
 const r=page.request;
 expect((await r.get('/api/audit')).status()).toBe(401);
 await r.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}});
 const patient=await (await r.post('/api/patients',{data:{age:28,language:'en',consent:true}})).json();
 const encounter=await (await r.post('/api/encounters',{data:{patientId:patient.data.id,text:'I have fever for two days.',language:'en',inputType:'text'}})).json(),id=encounter.data.id;
 expect((await r.post('/api/triage/analyze',{data:{encounterId:id}})).status()).toBe(200);
 for(let i=0;i<52;i++)expect((await r.get(`/api/audit/${id}?limit=1`)).status()).toBe(200);
 await page.goto(`/audit?encounterId=${id}`);await expect(page.locator('tbody tr')).toHaveCount(50);
 const older=page.getByRole('button',{name:'Load older audit events'});await expect(older).toBeEnabled();
 await page.route('**/api/audit/**',route=>route.request().url().includes('cursor=')?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:{message:'Audit unavailable.'}})}):route.continue());
 await older.click();await expect(page.locator('p[role=alert]')).toContainText('Audit unavailable.');await expect(page.locator('tbody tr')).toHaveCount(50);await expect(older).toBeEnabled();
 await page.unroute('**/api/audit/**');await older.click();await expect(page.locator('tbody')).toContainText('TRIAGE_COMPLETED');
 const eventIds=await page.locator('tbody details > p.mono').allTextContents();expect(new Set(eventIds).size).toBe(eventIds.length);expect(eventIds.length).toBeGreaterThan(50);
 await page.context().clearCookies();await page.getByRole('button',{name:'Refresh audit'}).click();await expect(page.locator('p[role=alert]')).toContainText('Sign in is required.');await expect(page.locator('tbody tr')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Case priority and referral'})).toHaveCount(0);
});
