import {test,expect} from '@playwright/test';
test('pending screen retries a failed sync and changes only after server confirmation',async({page})=>{
 expect((await page.request.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}})).status()).toBe(200);
 await page.goto('/intake');await page.getByRole('button',{name:'Simulate offline',exact:true}).click();await page.getByRole('spinbutton',{name:'Age',exact:true}).fill('42');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Continue to intake'}).click();await page.getByLabel('Original words / reviewed transcript').fill('Cough for two days.');await page.getByRole('button',{name:'Save intake'}).click();await page.getByRole('button',{name:'Save encrypted draft for sync'}).click();await expect(page.getByRole('heading',{name:'PENDING SYNC',exact:true})).toBeVisible();
 let patients=0,encounters=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/patients'))patients++;if(request.method()==='POST'&&request.url().endsWith('/api/encounters'))encounters++;});
 let triages=0;await page.route('**/api/triage/analyze',async route=>{triages++;await route.fetch();await route.abort();});await page.getByRole('button',{name:'Reconnect and sync intake',exact:true}).click();await expect(page.locator('p.error[role=alert]')).toContainText('Your encrypted draft is retained');await expect(page.getByRole('heading',{name:'PENDING SYNC',exact:true})).toBeVisible();expect(patients).toBe(1);expect(encounters).toBe(1);
 await page.unroute('**/api/triage/analyze');await page.getByRole('button',{name:'Reconnect and sync intake',exact:true}).click();await expect(page.getByRole('heading',{name:'Ready for review',exact:true})).toBeVisible();const link=page.getByRole('link',{name:'Open triage card'});await expect(link).toHaveAttribute('href',/\/encounters\/.+/);expect(patients).toBe(1);expect(encounters).toBe(1);expect(triages).toBe(1);await link.click();await expect(page.locator('.priority-word')).toContainText('GREEN');
});
test('saved drafts survive reload and sync directly from the reviewer queue',async({page})=>{
 await page.request.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}});await page.goto('/intake');await page.getByRole('button',{name:'Simulate offline',exact:true}).click();await page.getByRole('spinbutton',{name:'Age',exact:true}).fill('39');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Continue to intake'}).click();await page.getByLabel('Original words / reviewed transcript').fill('Cough for two days.');await page.getByRole('button',{name:'Save intake'}).click();await page.getByRole('button',{name:'Save encrypted draft for sync'}).click();await expect(page.getByRole('heading',{name:'PENDING SYNC',exact:true})).toBeVisible();await page.reload();await page.goto('/queue');await page.getByLabel('Waiting-time order').selectOption('newest');
 let encounterId='';page.on('request',r=>{if(r.url().endsWith('/api/encounters')&&r.method()==='POST')encounterId=r.postDataJSON().clientRequestId;});await page.getByRole('button',{name:'Reconnect and sync saved drafts'}).click();await expect(page.getByRole('heading',{name:'On this device · PENDING SYNC'})).not.toBeVisible();await expect(page.getByRole('link',{name:'Open synced intake'})).toHaveAttribute('href',/\/encounters\/.+/);await expect(page.locator(`tbody a[href="/encounters/${encounterId}"]`)).toBeVisible();
});
