import {test,expect} from '@playwright/test';
test('workflow scroll animation reaches the last step and adapts to mobile',async({page},testInfo)=>{
 await page.setViewportSize({width:1280,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/');const section=page.locator('#intake-journey');await expect(section).toHaveClass(/flow-enhanced/);await expect(page.getByRole('heading',{name:'Many ways to tell a story.'})).toHaveCount(0);
 const geometry=await section.evaluate(el=>({top:el.getBoundingClientRect().top+window.scrollY,distance:el.getBoundingClientRect().height-window.innerHeight}));await page.evaluate(y=>window.scrollTo(0,y),geometry.top);
 await expect.poll(()=>section.locator('.flow-item').first().locator('h3').evaluate(el=>[...el.children].every(word=>Number(getComputedStyle(word).opacity)>0.98))).toBe(true);await page.screenshot({path:testInfo.outputPath('timeline-desktop-start.png')});await page.evaluate(y=>window.scrollTo(0,y),geometry.top+geometry.distance/2);await expect.poll(()=>page.locator('.flow-track').evaluate(el=>new DOMMatrix(getComputedStyle(el).transform).m41)).toBeLessThan(-50);
 await page.screenshot({path:testInfo.outputPath('timeline-desktop-middle.png')});await page.evaluate(y=>window.scrollTo(0,y),geometry.top+geometry.distance-1);
 await expect.poll(()=>section.locator('.flow-item').last().evaluate(el=>el.getBoundingClientRect().right)).toBeLessThan(1280);await expect.poll(()=>section.locator('.flow-item').last().evaluate(el=>el.getBoundingClientRect().left)).toBeGreaterThan(0);await expect.poll(()=>section.locator('.flow-item').last().locator('h3').evaluate(el=>[...el.children].every(word=>Number(getComputedStyle(word).opacity)>0.98))).toBe(true);await page.screenshot({path:testInfo.outputPath('timeline-desktop-end.png')});
 expect(await section.locator('.flow-copy').evaluateAll(items=>items.filter(el=>el.scrollHeight>el.clientHeight+2).length)).toBe(0);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect(section).toHaveClass(/flow-enhanced/);expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)).toBe(false);await page.evaluate(()=>{const section=document.querySelector('#intake-journey')!;window.scrollTo(0,section.getBoundingClientRect().top+window.scrollY);});await page.screenshot({path:testInfo.outputPath('timeline-mobile-dark.png')});
});
test('reduced motion keeps the complete workflow readable without pinning',async({page})=>{
 await page.setViewportSize({width:1280,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');const section=page.locator('#intake-journey');await expect(section).not.toHaveClass(/flow-enhanced/);await expect(section.locator('.flow-item')).toHaveCount(7);expect(await section.locator('.flow-track').evaluate(el=>getComputedStyle(el).transform)).toBe('none');await expect(section.getByRole('heading',{name:'Consent before handover'})).toBeVisible();
});

for(const viewport of [{width:906,height:698},{width:390,height:698}]){test('animation is enabled at '+viewport.width+'x'+viewport.height,async({page},testInfo)=>{await page.setViewportSize(viewport);await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/');const section=page.locator('#intake-journey');await expect(section).toHaveClass(/flow-enhanced/);const geometry=await section.evaluate(el=>({top:el.getBoundingClientRect().top+window.scrollY,distance:el.getBoundingClientRect().height-window.innerHeight}));await page.evaluate(y=>window.scrollTo(0,y),geometry.top+geometry.distance*.6);await expect.poll(()=>section.locator('.flow-track').evaluate(el=>new DOMMatrix(getComputedStyle(el).transform).m41)).toBeLessThan(-50);expect(await section.locator('.flow-copy').evaluateAll(items=>items.filter(el=>el.scrollHeight>el.clientHeight+2).length)).toBe(0);expect(await section.locator('.flow-ending').evaluate(el=>el.getBoundingClientRect().bottom)).toBeLessThanOrEqual(viewport.height);await page.screenshot({path:testInfo.outputPath('compact-timeline.png')});});}
