import {test,expect} from '@playwright/test';
test('Hindi and Odia switch instantly, persist on reload and fit mobile in both themes',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.locator('.language-switcher select').selectOption('hi');
 await expect(page.locator('html')).toHaveAttribute('lang','hi');
 await expect(page.locator('h1')).toContainText('व्यक्ति की बात सुनें।');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','hi');
 await page.locator('.language-switcher select').selectOption('or');
 await expect(page.locator('h1')).toContainText('ବ୍ୟକ୍ତିଙ୍କ କଥା ଶୁଣନ୍ତୁ।');
 await expect(page.locator('.localized-safety-lines')).toContainText('ସୁରକ୍ଷା ସର୍ବଦା ଦୃଶ୍ୟମାନ');
 await page.setViewportSize({width:375,height:812});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('button',{name:'ନେଭିଗେସନ୍ ଖୋଲନ୍ତୁ'}).click();
 await expect(page.getByRole('link',{name:'ସମୀକ୍ଷା ତାଲିକା',exact:true}).last()).toBeVisible();
 await page.getByRole('button',{name:'ବନ୍ଦ କରନ୍ତୁ',exact:true}).click();
 await page.locator('header button').filter({has:page.locator('svg.lucide-moon')}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.goto('/privacy');await expect(page.locator('h1')).toContainText('ଗୋପନୀୟତା');
 await page.locator('.language-switcher select').selectOption('en');
 await page.goto('/');await expect(page.locator('h1')).toContainText('Hear the person.');
 expect(errors).toEqual([]);
});

test('switching the interface preserves patient fields, patient language and server enums',async({page})=>{
 expect((await page.request.post('/api/auth/credentials',{data:{username:'health.worker',password:'HealthWorker!2026'}})).status()).toBe(200);
 await page.goto('/intake');
 await page.getByLabel('Patient name',{exact:true}).fill('Language Test Patient');
 await page.getByLabel('Age',{exact:true}).fill('35');
 await page.getByLabel('Preferred language').selectOption('hi');
 await page.locator('main input[type=checkbox]').check();
 await page.locator('.language-switcher select').selectOption('or');
 await expect(page.locator('main input[maxlength="200"]')).toHaveValue('Language Test Patient');
 await expect(page.locator('main input[type=number]')).toHaveValue('35');
 await expect(page.locator('main select')).toHaveValue('hi');
 await expect(page.locator('main input[type=checkbox]')).toBeChecked();
 const saved=page.waitForResponse(r=>r.url().endsWith('/api/patients')&&r.request().method()==='POST');
 await page.locator('main .actions button').click();
 const patient=(await saved).request().postDataJSON();
 expect(patient.name).toBe('Language Test Patient');expect(patient.language).toBe('hi');
 await page.locator('main textarea').fill('Patient original words: cough for two days.');
 await page.locator('main .actions button').click();
 await page.locator('.language-switcher select').selectOption('hi');
 await expect(page.locator('h2').first()).toContainText('रिपोर्ट');
 await page.goto('/queue');
 await expect(page.locator('h1')).toContainText('समीक्षा सूची');
 const status=page.locator('select').filter({has:page.locator('option[value="INPUT_CAPTURED"]')});
 await status.selectOption('INPUT_CAPTURED');await expect(status).toHaveValue('INPUT_CAPTURED');
 await page.locator('select').filter({has:page.locator('option[value="newest"]')}).selectOption('newest');
 await expect(page.getByText('Language Test Patient',{exact:true}).first()).toBeVisible();
 const queue=(await (await page.request.get('/api/queue?state=INPUT_CAPTURED&sort=newest')).json()).data;
 expect(queue.some((row:{patient:{name:string};encounter:{state:string}})=>row.patient.name==='Language Test Patient'&&row.encounter.state==='INPUT_CAPTURED')).toBe(true);
});
