'use client';
import {useEffect,useState} from 'react';
type Event={id:string;userId:string|null;encounterId:string|null;action:string;timestamp:string;metadata:Record<string,unknown>};
export function AuditView(){
 const [events,setEvents]=useState<Event[]>([]);
 const [error,setError]=useState('');
 const [filter,setFilter]=useState('');
 const [role,setRole]=useState('');
 const [purgeId,setPurgeId]=useState('');
 const [busy,setBusy]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('encounterId');if(id)setPurgeId(id);fetch(id?`/api/audit/${id}`:'/api/audit').then(r=>r.json()).then(v=>v.ok?setEvents(v.data):setError(v.error.message)).catch(()=>setError('Audit events unavailable.'));fetch('/api/session').then(r=>r.json()).then(v=>setRole(v.data?.role??'')).catch(()=>{});},[]);
 async function purge(){if(!purgeId.trim()||!window.confirm(`Purge clinical data for ${purgeId}? The audit tombstone will remain.`))return;setBusy(true);setError('');try{const response=await fetch('/api/privacy/purge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({encounterId:purgeId.trim()})});const value=await response.json();if(!value.ok)throw new Error(`${value.error.code}: ${value.error.message}`);window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Purge failed');setBusy(false);}}
 return <div className="stack"><section className="panel"><h2 className="section-title">Stored information</h2><p>Anonymous patient ID, age, preferred language, consent state, original intake text, report text, structured note, review changes and audit events. No names, phone numbers or addresses are requested.</p><p>In mock mode, no source data is sent to an AI provider. In live mode, configured providers receive the minimum source content needed. Prototype retention is controlled by the local database operator.</p></section>{role==='administrator'&&<section className="panel"><h2 className="section-title">Purge an encounter</h2><p className="small">Removes clinical records and local source files. A non-identifying audit tombstone remains.</p><label className="field">Encounter ID<input value={purgeId} onChange={e=>setPurgeId(e.target.value)}/></label><div className="actions"><button className="btn danger" disabled={busy||!purgeId.trim()} onClick={purge}>{busy?'Purging…':'Purge encounter'}</button></div></section>}<label className="field">Filter events<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Action, encounter ID or actor"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="table-wrap"><table><thead><tr><th>When</th><th>Action</th><th>Actor</th><th>Encounter</th><th>Details</th></tr></thead><tbody>{events.filter(e=>`${e.action} ${e.encounterId} ${e.userId}`.toLowerCase().includes(filter.toLowerCase())).map(e=><tr key={e.id}><td className="mono">{new Date(e.timestamp).toLocaleString()}</td><td>{e.action}</td><td className="mono">{e.userId??'system'}</td><td className="mono">{e.encounterId??'—'}</td><td className="small">{JSON.stringify(e.metadata)}</td></tr>)}</tbody></table>{events.length===0&&!error&&<p className="panel muted">No audit events yet.</p>}</div></div>;
}
