'use client';
import {T} from '@/components/language-provider';

import {useEffect,useState} from 'react';
type Facility={name:string;type:string;location:string;settings:{legalIdentity:string;privacyContact:string;retentionDays:number;processors:string[];consentNotice:string;incidentContact:string}};
const empty:Facility={name:'',type:'',location:'',settings:{legalIdentity:'',privacyContact:'',retentionDays:30,processors:[],consentNotice:'',incidentContact:''}};
export function FacilitySettings(){const [value,setValue]=useState(empty),[editable,setEditable]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false);useEffect(()=>{Promise.all([fetch('/api/settings/facility').then(r=>r.json()),fetch('/api/session').then(r=>r.json())]).then(([facility,session])=>{if(!facility.ok)throw new Error(facility.error.message);setValue({name:facility.data.name,type:facility.data.type,location:facility.data.location,settings:{...empty.settings,...facility.data.settings}});setEditable(session.data?.role==='administrator');setLoaded(true);}).catch(error=>setMessage(error.message));},[]);
async function save(){try{const response=await fetch('/api/settings/facility',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});const payload=await response.json();if(!payload.ok)throw new Error(payload.error.message);setMessage('Facility settings saved and audited.');}catch(error){setMessage(error instanceof Error?error.message:'Save failed');}}
return <section className="panel stack"><h2 className="section-title"><T text={"Facility profile and governance"}/></h2>{loaded&&<>{(['name','type','location'] as const).map(key=><label className="field" key={key}><T text={key}/><input disabled={!editable} value={value[key]} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}{(['legalIdentity','privacyContact','incidentContact','consentNotice'] as const).map(key=><label className="field" key={key}><T text={key.replace(/([A-Z])/g,' $1')}/><textarea disabled={!editable} value={value.settings[key]} onChange={e=>setValue({...value,settings:{...value.settings,[key]:e.target.value}})}/></label>)}<label className="field"><T text={"Retention period in days"}/><input disabled={!editable} type="number" min="1" value={value.settings.retentionDays} onChange={e=>setValue({...value,settings:{...value.settings,retentionDays:Number(e.target.value)}})}/></label><label className="field"><T text={"Approved processors (one per line)"}/><textarea disabled={!editable} value={value.settings.processors.join('\n')} onChange={e=>setValue({...value,settings:{...value.settings,processors:e.target.value.split('\n').filter(Boolean)}})}/></label>{editable&&<button className="btn" onClick={save}><T text={"Save facility settings"}/></button>}<p className="small"><T text={"Provider credentials and deployment settings belong in the deployment secret store. Facility retention settings are used by the retention job."}/></p></>}{message&&<p role="status"><T text={message}/></p>}</section>;
}
