'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {useMemo,useRef} from 'react';
import * as THREE from 'three';
type Props={progress:number;pointer:{x:number;y:number};active:boolean};
const vertex=`attribute vec3 target; uniform float uProgress; uniform float uTime; varying float vFade; void main(){float t=smoothstep(0.0,1.0,uProgress);vec3 p=mix(position,target,t);p.y+=sin(uTime*0.28+position.x*2.0)*0.03*(1.0-t);vec4 mv=modelViewMatrix*vec4(p,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(7.0/-mv.z,1.2,4.0);vFade=0.5+0.5*t;}`;
const fragment=`varying float vFade; void main(){float d=length(gl_PointCoord-vec2(0.5));float alpha=smoothstep(0.5,0.05,d)*vFade;gl_FragColor=vec4(0.12,0.35,0.28,alpha);}`;
function Threads({progress,pointer}:Omit<Props,'active'>){const material=useRef<THREE.ShaderMaterial>(null);const {geometry,lines}=useMemo(()=>{let seed=43;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const count=470;const positions=new Float32Array(count*3);const targets=new Float32Array(count*3);const linePositions=new Float32Array(count*6);for(let i=0;i<count;i++){const x=-3+rand()*3.2,y=(rand()-.5)*3.6,z=(rand()-.5)*1.5;const tx=1.25+(i%16)*.09,ty=(Math.floor(i/16)%24-12)*.10,tz=(rand()-.5)*.08;positions.set([x,y,z],i*3);targets.set([tx,ty,tz],i*3);linePositions.set([x,y,z,tx,ty,tz],i*6);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('target',new THREE.BufferAttribute(targets,3));const lineGeo=new THREE.BufferGeometry();lineGeo.setAttribute('position',new THREE.BufferAttribute(linePositions,3));return {geometry:geo,lines:lineGeo};},[]);useFrame(({clock,camera})=>{if(material.current){material.current.uniforms.uTime.value=clock.elapsedTime;material.current.uniforms.uProgress.value=progress;}camera.rotation.y=THREE.MathUtils.lerp(camera.rotation.y,pointer.x*.07,.03);camera.rotation.x=THREE.MathUtils.lerp(camera.rotation.x,-pointer.y*.07,.03);});return <><lineSegments geometry={lines}><lineBasicMaterial color="#8BA99C" transparent opacity={0.12} depthWrite={false}/></lineSegments><points geometry={geometry}><shaderMaterial ref={material} vertexShader={vertex} fragmentShader={fragment} uniforms={{uProgress:{value:0},uTime:{value:0}}} transparent depthWrite={false} blending={THREE.AdditiveBlending}/></points></>}
export function HeroScene(props:Props){return <Canvas className="hero-canvas" dpr={[1,1.75]} frameloop={props.active?'always':'never'} gl={{alpha:true,antialias:false,powerPreference:'low-power'}} camera={{position:[0,0,6],fov:58}}><Threads progress={props.progress} pointer={props.pointer}/></Canvas>}
