'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {offlineActive,queueIntake} from '@/lib/offline';
import {PerformancePanel} from './performance-panel';
import {FailurePanel} from './failure-panel';

type Step='consent'|'capture'|'report'|'processing'|'done';
type Api<T>={ok:true;data:T}|{ok:false;error:{code:string;message:string}};
const samples={hi:'मुझे चार दिन से बुखार है और तेज दर्द है।',or:'ମୋତେ ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ ହେଉଛି।',en:'I have had a mild cough for two days.'};
async function post<T>(url:string,body:unknown):Promise<T>{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json() as Api<T>;if(!payload.ok)throw new Error(`${payload.error.code}: ${payload.error.message}`);return payload.data;}

export function IntakeFlow(){
 const [hydrated,setHydrated]=useState(false);
 const [step,setStep]=useState<Step>('consent');
 const [consent,setConsent]=useState(false);
 const [age,setAge]=useState(46);
 const [language,setLanguage]=useState<'hi'|'or'|'en'>('hi');
 const [text,setText]=useState(samples.hi);
 const [report,setReport]=useState('');
 const [reportFile,setReportFile]=useState<File|null>(null);
 const [patientId,setPatientId]=useState('');
 const [encounterId,setEncounterId]=useState('');
 const [pendingDraft,setPendingDraft]=useState(false);
 const [pendingSync,setPendingSync]=useState(false);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [stage,setStage]=useState('');
 const [recording,setRecording]=useState(false);
 const [audioUrl,setAudioUrl]=useState('');
 const [audioBlob,setAudioBlob]=useState<Blob|null>(null);
 const [audioId,setAudioId]=useState('');
 const [speechSegments,setSpeechSegments]=useState<{text:string;confidence:number;start?:number;end?:number}[]>([]);
 const [uncertain,setUncertain]=useState<string[]>([]);
 const recorder=useRef<MediaRecorder|null>(null);
 const chunks=useRef<Blob[]>([]);
 const consentStart=useRef(0);
 const timings=useRef<{intakeMs?:number;ocrMs?:number;triageMs?:number}>({});
 useEffect(()=>setHydrated(true),[]);

 function changeLanguage(value:'hi'|'or'|'en'){setLanguage(value);setText(samples[value]);}
 async function recordConsent(){consentStart.current=performance.now();setError('');setBusy(true);try{if(offlineActive()){setPendingDraft(true);setStep('capture');return;}const patient=await post<{id:string}>('/api/patients',{age,language,consent});setPatientId(patient.id);setStep('capture');}catch(e){setError(e instanceof Error?e.message:'SAVE_FAILED');}finally{setBusy(false);}}
 async function capture(){setError('');setBusy(true);try{if(pendingDraft){setStep('report');return;}const encounter=await post<{id:string}>('/api/encounters',{patientId,text,language,inputType:audioId?'voice':'text',...(audioId?{audioId,speechSegments}:{})});setEncounterId(encounter.id);timings.current.intakeMs=performance.now()-consentStart.current;setStep('report');}catch(e){setError(e instanceof Error?e.message:'SAVE_FAILED');}finally{setBusy(false);}}
 async function analyze(){setBusy(true);setError('');setStep('processing');let timer:ReturnType<typeof setInterval>|undefined;try{if(pendingDraft){if(reportFile)throw new Error('Report files require a connection. Enter report text or reconnect before continuing.');await queueIntake({age,language,text,inputType:'text',report,consent:true});setPendingSync(true);setStep('done');return;}const ocrStart=performance.now();if(reportFile){setStage('Uploading report');const form=new FormData();form.set('encounterId',encounterId);form.set('file',reportFile);const upload=await fetch('/api/reports/upload',{method:'POST',body:form});const payload=await upload.json();if(!payload.ok)throw new Error(`${payload.error.code}: ${payload.error.message}`);setStage('Reading report');await post('/api/reports/ocr',{reportId:payload.data.reportId});}if(report.trim()){setStage('Reading report');await post('/api/reports/ocr',{encounterId,rawText:report});}if(reportFile||report.trim())timings.current.ocrMs=performance.now()-ocrStart;setStage('Normalizing');timer=setInterval(async()=>{try{const response=await fetch(`/api/encounters/${encounterId}`);const value=await response.json();if(value.ok&&value.data.encounter.state==='PROCESSING')setStage(value.data.encounter.status);}catch{}},450);const triageStart=performance.now();await post('/api/triage/analyze',{encounterId});timings.current.triageMs=performance.now()-triageStart;localStorage.setItem('sf_last_performance',JSON.stringify(timings.current));window.dispatchEvent(new Event('sf-perf'));setStep('done');}catch(e){setError(e instanceof Error?e.message:'Processing failed');setStep('report');}finally{if(timer)clearInterval(timer);setBusy(false);}}
 async function startRecording(){setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const media=new MediaRecorder(stream);recorder.current=media;media.ondataavailable=e=>chunks.current.push(e.data);media.onstop=()=>{const blob=new Blob(chunks.current,{type:media.mimeType});setAudioBlob(blob);setAudioUrl(URL.createObjectURL(blob));stream.getTracks().forEach(track=>track.stop());};media.start();setRecording(true);}catch{setError('Microphone access was denied. Enter the original words manually.');}}
 function stopRecording(){recorder.current?.stop();setRecording(false);}
 async function transcribe(){if(!audioBlob||!patientId)return;setBusy(true);setError('');try{const form=new FormData();form.set('audio',new File([audioBlob],'speech.webm',{type:audioBlob.type}));form.set('patientId',patientId);form.set('langHint',language);const response=await fetch('/api/speech/transcribe',{method:'POST',body:form});const value=await response.json();if(!value.ok)throw new Error(`${value.error.code}: ${value.error.message}`);setText(value.data.text);setAudioId(value.data.audioId);setSpeechSegments(value.data.segments);setUncertain(value.data.segments.filter((segment:{confidence:number})=>segment.confidence<0.7).map((segment:{text:string})=>segment.text));}catch(e){setError(e instanceof Error?e.message:'ASR_FAILED');}finally{setBusy(false);}}

 return <div className="grid-2"><div className="stack"><section className="panel"><div className="eyebrow">Step {step==='consent'?'1':step==='capture'?'2':step==='report'?'3':step==='processing'?'4':'5'} / 5</div>
 {step==='consent'&&<><h2 className="section-title">Consent & purpose</h2><p>This educational prototype stores an anonymous identifier, age, language, original intake text, report transcription, and reviewer actions. Information may be organised by AI in live mode. A qualified reviewer makes the final assessment.</p><div className="form-grid"><label className="field">Age<input type="number" min="0" max="120" value={age} onChange={e=>setAge(Number(e.target.value))}/></label><label className="field">Preferred language<select value={language} onChange={e=>changeLanguage(e.target.value as 'hi'|'or'|'en')}><option value="hi">Hindi</option><option value="or">Odia</option><option value="en">English</option></select></label></div><div className="divider"/><label className="check"><input type="checkbox" disabled={!hydrated} checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Consent to record and organise this information for qualified staff review has been obtained.</span></label><div className="actions"><button className="btn" disabled={!consent||busy||age<0||age>120} onClick={recordConsent}>{busy?'Saving consent…':'Continue to intake →'}</button></div></>}
 {step==='capture'&&<><h2 className="section-title">Capture the concern</h2><div className="notice small">Consent {pendingDraft?'will be queued on this device':'recorded'} · Age {age} · {language.toUpperCase()}</div><p className="small muted">Use the synthetic sample, edit the original words, or record a local clip. Review the transcript before continuing.</p><button type="button" className={`record ${recording?'active':''}`} aria-label={recording?'Stop recording':'Start recording'} onClick={recording?stopRecording:startRecording}>{recording?'■':'●'}</button>{audioUrl&&<div className="stack"><audio controls src={audioUrl}>Audio playback unavailable</audio><button className="btn secondary" disabled={busy||pendingDraft} title={pendingDraft?'Transcription requires an online, recorded consent. Enter text manually.':undefined} onClick={transcribe}>Transcribe recording</button></div>}{uncertain.map((phrase,i)=><p key={i} className="badge yellow">Possibly {phrase} · Check audio</p>)}<label className="field" style={{marginTop:20}}>Original words / reviewed transcript<textarea lang={language} value={text} onChange={e=>setText(e.target.value)}/></label><div className="actions"><button className="btn" disabled={busy||!text.trim()} onClick={capture}>{busy?'Saving…':'Save intake →'}</button></div></>}
 {step==='report'&&<><h2 className="section-title">Report & extraction</h2><p>Upload a synthetic PNG, JPEG, or PDF, enter report text, or continue without a report. The source remains linked to the encounter.</p><label className="field">Upload report<input type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>setReportFile(e.target.files?.[0]??null)}/></label>{reportFile&&<p className="small mono">Selected: {reportFile.name} · {Math.round(reportFile.size/1024)} KB</p>}<label className="field">Report text<textarea value={report} onChange={e=>setReport(e.target.value)} placeholder="Optional synthetic report transcription"/></label><button className="text-link" type="button" onClick={()=>setReport('Synthetic CBC report\nHaemoglobin: 9.2 g/dL\nSample date: 14 September 2026')}>Use synthetic CBC example</button><div className="actions"><button className="btn" disabled={busy} onClick={analyze}>Organise for review →</button></div></>}
 {step==='processing'&&<><h2 className="section-title">Organising information</h2><p role="status" aria-live="polite">{stage||'Preparing sources'}</p><div className="wave" aria-hidden="true">{Array.from({length:25},(_,i)=><span key={i} style={{'--height':`${10+(i*17)%32}px`} as React.CSSProperties}/>)}</div></>}
 {step==='done'&&<><h2 className="section-title">{pendingSync?'PENDING SYNC':'Ready for review'}</h2><p>{pendingSync?'This intake is stored on this device and has not been confirmed by the server. Reconnect and use the header sync control.':'Encounter saved. The priority and source links are available to the reviewer.'}</p><div className="actions">{!pendingSync&&<Link className="btn" href={`/encounters/${encounterId}`}>Open triage card →</Link>}<Link className="btn secondary" href="/queue">Reviewer queue</Link></div></>}
 {error&&<p className="error" role="alert">{error}</p>}</section></div><aside className="stack"><section className="panel"><h2 className="section-title">What is stored</h2><p className="small">Anonymous ID, age, language, consent, original text, report transcription, structured note, and audit events. No name, phone number, or address.</p></section><section className="panel"><h2 className="section-title">Review boundary</h2><p className="small">AI organises details. Configured rules flag review priority. Qualified staff decide what to do next.</p></section><PerformancePanel/><FailurePanel encounterId={encounterId}/></aside></div>;
}
