'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Row={encounter:{id:string;priorityFinal:string|null;state:string;createdAt:string};patient:{anonymousPatientId:string;preferredLanguage:string};inputType:string};
export function QueueTable(){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[page,setPage]=useState(0),[tick,setTick]=useState(Date.now()),[selected,setSelected]=useState(0);
 const [filters,setFilters]=useState({priority:'ALL',language:'ALL',state:'ALL',inputType:'ALL',sort:'oldest'});
 useEffect(()=>{const controller=new AbortController();fetch('/api/queue?'+new URLSearchParams({...filters,page:String(page)}),{signal:controller.signal}).then(r=>r.json()).then(v=>{if(v.ok){setRows(v.data);setError('');setSelected(0);}else setError(v.error.message);}).catch(e=>{if(e.name!=='AbortError')setError('Queue unavailable.');});return()=>controller.abort();},[filters,page]);
 useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.target instanceof HTMLElement&&(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)))return;if(e.key==='j')setSelected(n=>Math.min(rows.length-1,n+1));if(e.key==='k')setSelected(n=>Math.max(0,n-1));if(e.key==='Enter'&&rows[selected])window.location.href='/encounters/'+rows[selected].encounter.id;}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[rows,selected]);
 const options={priority:['ALL','RED','YELLOW','GREEN','PRIORITY_UNAVAILABLE'],language:['ALL','en','hi','or'],state:['ALL','INPUT_CAPTURED','TRIAGED','IN_REVIEW','INFO_REQUESTED','APPROVED','ESCALATED','REFERRAL_GENERATED','COMPLETED','ASR_FAILED','OCR_FAILED','AI_FAILED','TRIAGE_FAILED','SAFETY_ENGINE_FAILED','SAVE_FAILED'],inputType:['ALL','text','voice'],sort:['oldest','newest']};
 const labels={priority:'Priority',language:'Language',state:'Status',inputType:'Input type',sort:'Waiting-time order'};
 return <div className="stack"><div className="form-grid">{(Object.keys(options) as (keyof typeof options)[]).map(key=><label className="field" key={key}>{labels[key]}<select value={filters[key]} onChange={e=>{setPage(0);setFilters({...filters,[key]:e.target.value});}}>{options[key].map(v=><option key={v} value={v}>{v==='ALL'?'All':v==='oldest'?'Longest waiting first':v==='newest'?'Newest first':v}</option>)}</select></label>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Priority</th><th>Patient</th><th>Language</th><th>Input</th><th>Status</th><th>Waiting</th><th>Open</th></tr></thead><tbody>{rows.map((row,index)=>{const p=row.encounter.priorityFinal??'PRIORITY_UNAVAILABLE';return <tr key={row.encounter.id} className={p==='RED'?'pinned':''} aria-selected={selected===index}><td><span className={'badge '+(p==='RED'?'red':p==='YELLOW'?'yellow':p==='GREEN'?'green':'unavailable')}>{p}</span></td><td className="mono">{row.patient.anonymousPatientId}</td><td>{row.patient.preferredLanguage.toUpperCase()}</td><td>{row.inputType}</td><td>{row.encounter.state}</td><td>{Math.max(0,Math.floor((tick-new Date(row.encounter.createdAt).getTime())/60000))} min</td><td><Link className="text-link" href={'/encounters/'+row.encounter.id}>Review →</Link></td></tr>})}</tbody></table>{!rows.length&&<p className="panel muted">No cases match these filters.</p>}</div><div className="actions"><button className="btn secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Previous page</button><span>Page {page+1}</span><button className="btn secondary" disabled={rows.length<50} onClick={()=>setPage(page+1)}>Next page</button><Link className="text-link" href="/analytics">Reviewer analytics →</Link></div><p className="small">RED cases remain first in either waiting-time order. Keyboard: j / k selects a row; Enter opens it.</p><p className="small">AI-generated review priority. Not a medical diagnosis. Final assessment must be made by qualified healthcare staff.</p></div>;
}
