'use client';
import {T,useUiLanguage} from '@/components/language-provider';

import {useCallback,useEffect,useState} from 'react';
import type {Recipient} from './referral-directory';
import type {ReferralReport} from '@/lib/referral-policy';
import {deliveryLabels} from '@/lib/referral-delivery-config';
type Saved={id:string;content:string;deliveryStatus:string;recipientId:string;decision:string|null};
export function ReferralPanel({id,state,age,onSaved}:{id:string;state:string;age:number;onSaved:()=>Promise<void>}){const {t:uiText}=useUiLanguage();
 const [doctor,setDoctor]=useState(false),[recipients,setRecipients]=useState<Recipient[]>([]),[rows,setRows]=useState<Saved[]>([]),[recipientId,setRecipientId]=useState(''),[reason,setReason]=useState(''),[consent,setConsent]=useState(false),[includeName,setIncludeName]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [connections,setConnections]=useState<Record<string,string>>({}),[electronicConsent,setElectronicConsent]=useState<Record<string,boolean>>({});
 const [sources,setSources]=useState<{id:string;fileName:string;documentType:string}[]>([]);
 const load=useCallback(async()=>{const s=await (await fetch('/api/reviews/workspace')).json();setDoctor(s.data?.role==='medical_officer');if(s.data?.role!=='medical_officer')return;const [directory,saved,config]=await Promise.all([fetch('/api/referral-recipients').then(r=>r.json()),fetch(`/api/referrals?encounterId=${id}`).then(r=>r.json()),fetch('/api/referrals/delivery-config').then(r=>r.json())]);if(directory.ok)setRecipients(directory.data.filter((r:Recipient)=>r.active));if(saved.ok)setRows(saved.data);if(config.ok)setConnections(Object.fromEntries(config.data.map((c:{recipientId:string;mode:string})=>[c.recipientId,c.mode])));},[id]);
 useEffect(()=>{load().catch(()=>setError('Referral workspace unavailable.'));},[load,state]);
 useEffect(()=>{setConsent(false);},[recipientId,includeName,reason]);
 useEffect(()=>{fetch(`/api/encounters/${id}`).then(r=>r.json()).then(v=>{if(v.ok)setSources(v.data.reports.filter((r:{fileUrl:string|null})=>r.fileUrl));}).catch(()=>setError('Source document list unavailable. Reload before sharing.'));},[id]);
 async function create(){setBusy(true);setError('');try{const v=await (await fetch('/api/referrals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({encounterId:id,recipientId,reason,consentConfirmed:consent,consentAuthority:age<18?'guardian':'self',includeName})})).json();if(!v.ok)throw new Error(v.error.message);setConsent(false);await onSaved();await load();}catch(e){setError(e instanceof Error?e.message:'Referral could not be created.');}finally{setBusy(false);}}
 async function send(row:Saved){setBusy(true);setError('');try{const v=await (await fetch(`/api/referrals/${row.id}/send`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({electronicConsentConfirmed:electronicConsent[row.id]===true,includeAttachments:true,consentAuthority:age<18?'guardian':'self'})})).json();if(!v.ok)throw new Error(v.error.message);setElectronicConsent(s=>({...s,[row.id]:false}));await load();await onSaved();}catch(e){setError(e instanceof Error?e.message:'Delivery unconfirmed.');}finally{setBusy(false);}}
 async function download(row:Saved){setBusy(true);setError('');try{const response=await fetch(`/api/referrals/${row.id}/download`);if(!response.ok){const v=await response.json();throw new Error(v.error.message);}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`referral-${row.id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Download failed.');}finally{setBusy(false);}}
 if(!doctor)return null;const approved=['APPROVED','REFERRAL_GENERATED'].includes(state),selected=recipients.find(r=>r.id===recipientId);
 return <section id="referral" className="panel scroll-mt-6"><h2 className="section-title"><T text={"Doctor-approved referral"}/></h2><p className="small muted"><T text={"Print or download a confidential report. Send the report and uploaded prescriptions/documents to one receiving SwasthyaFlow workspace after separate consent. Receiving doctors accept or decline the referral."}/></p>{error&&<p className="error" role="alert"><T text={error}/></p>}{approved?<div className="stack">{!recipients.length&&<p className="muted"><T text={"Ask an administrator to add a verified hospital, PSU or specialist in Settings."}/></p>}<label className="field"><T text={"Referral recipient"}/><select value={recipientId} onChange={e=>setRecipientId(e.target.value)}><option value=""><T text={"Select verified recipient"}/></option>{recipients.map(r=><option key={r.id} value={r.id}>{r.name} · {r.department}</option>)}</select></label><label className="field"><T text={"Factual referral reason"}/><textarea value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} placeholder={uiText("Reason for qualified review; no diagnosis or treatment instructions")}/></label><label><input type="checkbox" checked={includeName} onChange={e=>setIncludeName(e.target.checked)}/> <T text={" Include recorded patient name in this recipient’s report"}/></label><p className="small"><T text={"Includes age, patient reference, language, approved summary, review priority, referral reason and referring doctor."}/></p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={!selected||reason.trim().length<10}/> <T text={" I explained this report’s contents and recipient ("}/>{selected?.name??<T text={'not selected'}/>}<T text={") and recorded "}/>{age<18?<T text={'guardian'}/>:<T text={'patient'}/>} <T text={" consent for its confidential handover. Intake consent alone does not authorize this referral."}/></label><button className="btn" onClick={create} disabled={busy||!selected||!consent||reason.trim().length<10}><T text={"Create referral report"}/></button></div>:<p className="muted"><T text={"Approve the reviewed case before creating a referral."}/></p>}
 {rows.map(row=>{const report=JSON.parse(row.content) as ReferralReport,mode=connections[row.recipientId];return <article key={row.id} className="panel"><strong>{report.recipient.name}</strong><p className="small mono"><T text={deliveryLabels[row.deliveryStatus]??row.deliveryStatus}/> <T text={"  "}/>{row.decision&&<> · <T text={row.decision}/></>} · {new Date(report.createdAt).toLocaleString()}</p><p className="small">{report.reason}</p><details><summary><T text={"Review report contents"}/></summary><p>{report.patient.reference}{report.patient.name?` · ${report.patient.name}`:<T text={''}/>} <T text={" · Age "}/>{report.patient.age}</p><p>{report.summary}</p><p><T text={"Priority: "}/><T text={report.priority}/> <T text={" · Doctor: "}/>{report.doctor}</p></details><button className="btn secondary" disabled={busy} onClick={()=>download(row)}><T text={"Download referral PDF"}/></button> <T text={"  "}/><a className="btn secondary" target="_blank" rel="noreferrer" href={`/api/referrals/${row.id}/download?print=1`}><T text={"Print referral report"}/></a>{row.deliveryStatus==='NOT_SENT'&&<div className="stack"><p className="small">{mode==='local'?<T text={'Prototype SwasthyaFlow receiving workspace; the named institution is not onboarded.'}/>:mode==='internal'?<T text={'Receiving SwasthyaFlow workspace configured.'}/>:<T text={'No receiving workspace configured.'}/>}</p><details><summary><T text={"Original documents to share ("}/>{sources.length})</summary>{sources.map(s=><p key={s.id}>{s.documentType} · {s.fileName}</p>)}{!sources.length&&<p><T text={"No uploaded originals. Only the referral report will be shared."}/></p>}</details><label><input type="checkbox" checked={electronicConsent[row.id]??false} onChange={e=>setElectronicConsent(s=>({...s,[row.id]:e.target.checked}))}/> <T text={" I explained the named recipient and recorded "}/>{age<18?<T text={'guardian'}/>:<T text={'patient'}/>} <T text={" consent to share this referral and all uploaded prescriptions and report documents electronically. These originals can contain identifiable information."}/></label><button className="btn" onClick={()=>send(row)} disabled={busy||!electronicConsent[row.id]||!['internal','local'].includes(mode)}><T text={"Send referral with documents"}/></button></div>}</article>;})}<a href="/referrals/inbox" className="text-link"><T text={"Open receiving inbox →"}/></a> <T text={"  "}/><button className="btn secondary" disabled={busy} onClick={()=>load().catch(()=>setError('Status unavailable.'))}><T text={"Refresh delivery status"}/></button></section>;
}




