'use client';
import {T,useUiLanguage} from '@/components/language-provider';

import {useState,useEffect,useCallback} from 'react';
export type Recipient={id:string;name:string;kind:string;institution:string;department:string;registrationNumber:string;verificationReference:string;active:boolean};
export function ReferralDirectory(){const {t:uiText}=useUiLanguage();
 const [workspaces,setWorkspaces]=useState<{id:string;name:string}[]>([]);
 const [rows,setRows]=useState<Recipient[]>([]),[admin,setAdmin]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const s=await (await fetch('/api/session')).json();setAdmin(s.data?.role==='administrator');if(s.data?.role==='administrator'){const v=await (await fetch('/api/referral-recipients')).json();if(v.ok)setRows(v.data);const w=await (await fetch("/api/referral-workspaces")).json();if(w.ok)setWorkspaces(w.data);}},[]);useEffect(()=>{load().catch(()=>setError('Directory unavailable.'));},[load]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setError('');try{const v=await (await fetch('/api/referral-recipients',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({receivingFacilityId:data.get('receivingFacilityId')||undefined,name:data.get('name'),kind:data.get('kind'),institution:data.get('institution'),department:data.get('department'),registrationNumber:data.get('registrationNumber'),verificationReference:data.get('verificationReference'),verified:data.get('verified')==='on'})})).json();if(!v.ok)throw new Error(v.error.message);form.reset();await load();}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 async function toggle(r:Recipient){setBusy(true);setError('');try{const v=await (await fetch('/api/referral-recipients',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:r.id,active:!r.active})})).json();if(!v.ok)throw new Error(v.error.message);await load();}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 return <section className="panel"><h2 className="section-title"><T text={"Referral directory"}/></h2><p className="small muted"><T text={"Facility administrators verify each hospital or specialist against official records. Government hospitals, PSU health services and specialists can be added. Electronic delivery requires a configured, approved receiver."}/></p>{error&&<p className="error" role="alert"><T text={error}/></p>}{admin?<><form onSubmit={save} className="stack"><label className="field"><T text={"Receiving SwasthyaFlow workspace"}/><select name="receivingFacilityId"><option value=""><T text={"Print/download only"}/></option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="field"><T text={"Recipient name"}/><input name="name" required minLength={3} maxLength={160}/></label><label className="field"><T text={"Recipient type"}/><select name="kind"><option value="government_hospital"><T text={"Government hospital"}/></option><option value="psu_hospital"><T text={"PSU hospital / health service"}/></option><option value="specialist"><T text={"Specialist doctor"}/></option></select></label><label className="field"><T text={"Hospital / institution"}/><input name="institution" required minLength={3} maxLength={160}/></label><label className="field"><T text={"Department / specialty"}/><input name="department" required minLength={2} maxLength={100}/></label><label className="field"><T text={"Specialist registration number"}/><input name="registrationNumber" maxLength={100}/><span className="small muted"><T text={"Required for a specialist."}/></span></label><label className="field"><T text={"Verification reference"}/><textarea name="verificationReference" required minLength={10} maxLength={500} placeholder={uiText("Official directory reference and date verified; no patient details")}/></label><label><input type="checkbox" name="verified" required/> <T text={" I verified the recipient’s identity, institution and referral acceptance through official channels."}/></label><button className="btn" disabled={busy}><T text={"Add verified recipient"}/></button></form><div className="divider"/>{rows.length?rows.map(r=><div key={r.id} className="panel"><strong>{r.name}</strong><p className="small mono"><T text={"Recipient ID: "}/>{r.id}</p><p className="small">{r.institution} · {r.department} · {r.active?<T text={'Active'}/>:<T text={'Inactive'}/>}</p><button className="btn secondary" disabled={busy} onClick={()=>toggle(r)}>{r.active?<T text={'Deactivate'}/>:<T text={'Reactivate'}/>} <T text={"  "}/>{r.name}</button></div>):<p className="muted"><T text={"No verified recipients yet."}/></p>}</>:<p className="muted"><T text={"An administrator manages this directory. Doctors select recipients on an approved case."}/></p>}</section>;
}


