'use client';
import {T} from '@/components/language-provider';

import {useState} from 'react';
export function ReviewerAuthorization({role,name,scoped,facility,onChanged}:{role:string;name:string;scoped:boolean;facility?:string;onChanged:()=>Promise<void>}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function open(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const v=await (await fetch('/api/reviews/workspace',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})})).json();setPassword('');if(!v.ok)throw new Error(v.error.message);await onChanged();}catch(e){setError(e instanceof Error?e.message:'Reviewer authorization unavailable.');}finally{setBusy(false);}}
 async function close(){setBusy(true);setError('');try{const response=await fetch('/api/reviews/workspace',{method:'DELETE'});if(!response.ok)throw new Error('Could not close reviewer authorization.');await onChanged();}catch(e){setError(e instanceof Error?e.message:'Authorization unavailable.');}finally{setBusy(false);}}
 return <section className="panel"><h2 className="section-title"><T text={"Reviewer authorization"}/></h2><p className="small"><T text={"Current reviewer: "}/>{name||'Checking credentials…'} · {role.replaceAll('_',' ')||'pending'}</p><p className="notice small"><T text={"Source facility: "}/><strong>{facility??'Checking facility…'}</strong><T text={". Use a reviewer account assigned to this facility."}/></p><p className="small"><T text={"Nurses can edit, request information and escalate. A Medical Officer must approve cases, override priority and create referrals. The reviewer must belong to this case’s facility."}/></p>{error&&<p role="alert" className="error"><T text={error}/></p>}{role!=='medical_officer'&&<form className="stack" onSubmit={open}><label className="field"><T text={"Reviewer username"}/><input value={username} onChange={e=>setUsername(e.target.value)} required autoComplete="username"/></label><label className="field"><T text={"Reviewer password"}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button className="btn" disabled={busy}>{busy?<T text={'Verifying reviewer…'}/>:<T text={'Authorize reviewer in this case'}/>}</button><p className="small muted"><T text={"Your main staff session stays signed in. The clinical action is attributed to the authenticated reviewer."}/></p></form>}{scoped&&<button className="btn secondary" disabled={busy} onClick={close}><T text={"Close reviewer authorization"}/></button>}</section>;
}
