'use client';
import {T} from '@/components/language-provider';

import {useState} from 'react';
import {structuredFactsSchema} from '@/lib/ai/types';
import {evidenceSchema,type Evidence} from '@/lib/facts';
type Draft={duration:string[];ambiguousInformation:string[];symptoms:string[];history:string[];medications:string[];timeline:string[];missingInformation:string[];followUpQuestions:string[];evidence:Evidence[]};
export function StructuredReview({id,fieldSources,timeline,missingInformation,followUpQuestions,enabled,onSaved}:{id:string;fieldSources:Record<string,unknown>;timeline:string[];missingInformation:string[];followUpQuestions:string[];enabled:boolean;onSaved:()=>Promise<void>}){
 const parsed=structuredFactsSchema.safeParse(fieldSources.facts);
 const parsedEvidence=evidenceSchema.array().safeParse(fieldSources.evidence);
 const [draft,setDraft]=useState<Draft>({duration:parsed.success?parsed.data.patient_reported.duration:[],ambiguousInformation:parsed.success?parsed.data.ambiguous_information:[],symptoms:parsed.success?parsed.data.patient_reported.symptoms:[],history:parsed.success?parsed.data.patient_reported.history:[],medications:parsed.success?parsed.data.patient_reported.medications:[],timeline,missingInformation,followUpQuestions,evidence:parsedEvidence.success?parsedEvidence.data:[]});
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function save(){setBusy(true);setMessage('');try{const response=await fetch('/api/reviews',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({encounterId:id,decision:'EDIT',fields:draft})});const value=await response.json();if(!value.ok)throw new Error(value.error.message);await onSaved();setMessage('Structured corrections saved. Safety rules were evaluated and the changes were audited.');}catch(error){setMessage(error instanceof Error?error.message:'Corrections could not be saved.');}finally{setBusy(false);}}
 const labels={duration:'Reported duration with units',ambiguousInformation:'Ambiguous information',symptoms:'Reported symptoms',history:'Reported history',medications:'Reported medicines',timeline:'Chronological events',missingInformation:'Missing information',followUpQuestions:'Follow-up questions'};
 return <section className="panel stack"><h2 className="section-title"><T text={"Structured facts and corrections"}/></h2><p className="small"><T text={"Each line is a separate fact. Compare changes with the original source. A lower priority requires the separate authorized override workflow."}/></p>{(Object.keys(labels) as (keyof typeof labels)[]).map(key=><label className="field" key={key}><T text={labels[key]}/><textarea disabled={!enabled||busy} value={draft[key].join('\n')} onChange={event=>setDraft({...draft,[key]:event.target.value.split('\n').filter(line=>line.trim())})}/></label>)}<h3><T text={"Information state"}/></h3>{draft.evidence.map((item,index)=><div className="panel" key={item.field}><label className="field">{item.field}<select disabled={!enabled||busy} value={item.state} onChange={event=>setDraft({...draft,evidence:draft.evidence.map((entry,i)=>i===index?{...entry,state:event.target.value as Evidence['state']}:entry)})}><option value={"KNOWN"}><T text={"KNOWN"}/></option><option value={"UNKNOWN"}><T text={"UNKNOWN"}/></option><option value={"UNCLEAR"}><T text={"UNCLEAR"}/></option></select></label><label className="field"><T text={"Recorded value"}/><input disabled={!enabled||busy} value={item.value} onChange={event=>setDraft({...draft,evidence:draft.evidence.map((entry,i)=>i===index?{...entry,value:event.target.value}:entry)})}/></label><p className="small"><T text={"Source: "}/>{item.source} · {item.quote||'No source information supplied'}</p></div>)}<details><summary><T text={"Inspect field provenance"}/></summary><pre className="source-details">{JSON.stringify(fieldSources.provenance??{},null,2)}</pre></details><button className="btn secondary" disabled={!enabled||busy} onClick={save}>{busy?<T text={'Saving corrections…'}/>:<T text={'Save structured corrections'}/>}</button>{message&&<p role="status"><T text={message}/></p>}</section>;
}
