import {z} from 'zod';
import {eq} from 'drizzle-orm';
import {db} from '@/lib/db/server';
import {encounters,patients,triageNotes,referrals,auditLogs} from '@/db/schema';
import {session,allowed} from '@/lib/auth';
import {failure,success,parseFailure} from '@/lib/api';
import {assertNonDiagnostic} from '@/lib/safety/resolve';
import {encounterForActor} from '@/lib/access';
const schema=z.object({encounterId:z.string().min(1),content:z.string().trim().min(20)}).strict();
export async function POST(req:Request){const actor=await session();if(!allowed(actor?.role??null,['medical_officer']))return failure('FORBIDDEN','Medical Officer role required.',403);try{const body=schema.parse(await req.json());assertNonDiagnostic(body.content);const conn=await db();const encounter=await encounterForActor(body.encounterId,actor!);if(!encounter)return failure('NOT_FOUND','Encounter not found.',404);if(!['APPROVED','ESCALATED','REFERRAL_GENERATED'].includes(encounter.state))return failure('REVIEW_REQUIRED','Approve or escalate before generating a referral.',422);await conn.transaction(async tx=>{await tx.insert(referrals).values({id:crypto.randomUUID(),encounterId:body.encounterId,content:body.content});await tx.update(encounters).set({state:'REFERRAL_GENERATED',status:'REFERRAL_GENERATED'}).where(eq(encounters.id,body.encounterId));await tx.insert(auditLogs).values({id:crypto.randomUUID(),userId:actor!.id,encounterId:body.encounterId,action:'REFERRAL_GENERATED',metadata:{}});});return success({content:body.content});}catch(e){if(e instanceof Error&&e.message==='AI_PARSE_FAILED')return failure('NON_DIAGNOSTIC_GUARD','Referral contains disallowed diagnosis or treatment language.',422);return parseFailure(e);}}
export async function GET(req:Request){const actor=await session();if(!actor)return failure('UNAUTHORIZED','Sign in is required.',401);const id=new URL(req.url).searchParams.get('encounterId');if(!id)return failure('VALIDATION_FAILED','Encounter ID required.',422);const conn=await db();const encounter=await encounterForActor(id,actor);if(!encounter)return failure('NOT_FOUND','Encounter not found.',404);const [[patient],[note]]=await Promise.all([conn.select().from(patients).where(eq(patients.id,encounter.patientId)).limit(1),conn.select().from(triageNotes).where(eq(triageNotes.encounterId,id)).limit(1)]);const content=`REFERRAL SUMMARY\n\nPatient ID: ${patient.anonymousPatientId}\nAge: ${patient.age}\nPreferred Language: ${patient.preferredLanguage}\n\nReason for Referral: Qualified review requested\n\nReported Symptoms: ${encounter.symptoms.join(', ')||'Unknown'}\n\nTimeline: ${encounter.timeline.join('; ')||'Unknown'}\n\nRelevant Available Information: ${note?.summary??'No structured note available'}\n\nUploaded Reports: Refer to source record\n\nMissing Information: ${note?.missingInformation.join('; ')||'Unknown'}\n\nFollow-up / Review Questions: ${note?.followUpQuestions.join('; ')||'Unknown'}\n\nAI Review Priority: ${encounter.priorityFinal??'PRIORITY_UNAVAILABLE'}\n\nAttachments: Source record\n\nReviewer Status: ${encounter.state}\n\nAI-assisted administrative summary. Clinical assessment and referral decision remain with qualified healthcare staff.`;return success({content});}
