import {type SyncedIntake} from './sync-status';
import Dexie,{type EntityTable} from 'dexie';
import {cachedOfflineActor,intakeActor,invalidateOfflineActor} from './session-client';
export {cachedOfflineActor,intakeActor,type OfflineActor} from './session-client';
type Media={name:string;type:string;base64:string;documentType?:'report'|'prescription'};
type IntakeData={consentAuthority?:'self'|'guardian';patientName?:string;documents?:{id:string;media:Media;saved?:boolean}[];age:number;language:'hi'|'or'|'en';text:string;inputType:'text'|'voice';report:string;consent:true;reportMedia?:Media;audioMedia?:Media;patientId:string;encounterId:string;reportId:string;audioId:string;patientSaved?:boolean;encounterSaved?:boolean;reportSaved?:boolean;audioSaved?:boolean};
export type PendingIntake={id:string;ownerId:string;facilityId:string;language:'hi'|'or'|'en';cipher:ArrayBuffer;iv:Uint8Array<ArrayBuffer>;createdAt:number;status:'PENDING_SYNC'|'SYNC_FAILED';error?:string};
class OfflineStore extends Dexie{pending!:EntityTable<PendingIntake,'id'>;keys!:EntityTable<{ownerId:string;key:CryptoKey},'ownerId'>;constructor(){super('SwasthyaFlowOffline');this.version(1).stores({pending:'id,createdAt,status'});this.version(2).stores({pending:'id,ownerId,createdAt,status',keys:'ownerId'});}}
export const offlineStore=new OfflineStore();
export function offlineActive(){return typeof navigator!=='undefined'&&(!navigator.onLine||localStorage.getItem('sf_simulate_offline')==='1');}
async function createKey(ownerId:string){const found=await offlineStore.keys.get(ownerId);if(found)return found.key;const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await offlineStore.keys.put({ownerId,key});return key;}
async function keyFor(ownerId:string){return navigator.locks?navigator.locks.request("sf-offline-key:"+ownerId,()=>createKey(ownerId)):createKey(ownerId);}
async function seal(ownerId:string,data:IntakeData){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(ownerId)},await keyFor(ownerId),new TextEncoder().encode(JSON.stringify(data)));return {iv,cipher};}
async function open(item:PendingIntake){if(!item.cipher)throw new Error('LEGACY_DRAFT_REQUIRES_MANUAL_REENTRY');const key=await offlineStore.keys.get(item.ownerId);if(!key)throw new Error('OFFLINE_KEY_UNAVAILABLE');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:item.iv,additionalData:new TextEncoder().encode(item.ownerId)},key.key,item.cipher);return JSON.parse(new TextDecoder().decode(plain)) as IntakeData;}
export async function pendingForActor(){const actor=cachedOfflineActor();return actor?(await offlineStore.pending.where('ownerId').equals(actor.id).sortBy('createdAt')).filter(item=>item.facilityId===actor.facilityId):[];}
export async function queueIntake(data:Omit<IntakeData,'patientId'|'encounterId'|'reportId'|'audioId'>,files?:{report?:File|null;documents?:{file:File;documentType:'report'|'prescription'}[];audio?:Blob|null}){
const actor=cachedOfflineActor();if(!actor||!['health_worker','nurse','medical_officer'].includes(actor.role))throw new Error('OFFLINE_AUTHORIZATION_REQUIRED');
async function media(file:Blob,name:string){if(file.size>18000000)throw new Error('OFFLINE_MEDIA_TOO_LARGE');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {name,type:file.type,base64:btoa(binary)};}
const retainedDocuments=await Promise.all((files?.documents??[]).map(async document=>({id:crypto.randomUUID(),media:{...await media(document.file,document.file.name),documentType:document.documentType}})));
const payload:IntakeData={...data,documents:retainedDocuments,patientId:crypto.randomUUID(),encounterId:crypto.randomUUID(),reportId:crypto.randomUUID(),audioId:crypto.randomUUID(),...(files?.report?{reportMedia:await media(files.report,files.report.name)}:{}),...(files?.audio?{audioMedia:await media(files.audio,'speech.webm')}:{})};
const item:PendingIntake={id:crypto.randomUUID(),ownerId:actor.id,facilityId:actor.facilityId,language:data.language,...await seal(actor.id,payload),createdAt:Date.now(),status:'PENDING_SYNC'};await offlineStore.pending.add(item);window.dispatchEvent(new Event('sf-offline-change'));return item.id;}
async function post(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!value.ok)throw new Error(value.error.code);return value.data;}
async function upload(url:string,item:IntakeData,media:Media,idName:string,id:string){const bytes=Uint8Array.from(atob(media.base64),c=>c.charCodeAt(0));const form=new FormData();form.set('encounterId',item.encounterId);form.set(idName,id);if(media.documentType)form.set('documentType',media.documentType);form.set('file',new File([bytes],media.name,{type:media.type}));const response=await fetch(url,{method:'POST',body:form});const value=await response.json();if(!value.ok)throw new Error(value.error.code);}
export async function syncPending():Promise<{synced:number;failed:number;error?:string}>{if(offlineActive())return {synced:0,failed:0};
const run=async()=>{const actor=await intakeActor().catch(()=>null);if(!actor||!['health_worker','nurse','medical_officer'].includes(actor.role))return {synced:0,failed:1,error:'OFFLINE_AUTHORIZATION_REQUIRED'};const items=await pendingForActor();let synced=0,failed=0;
for(const item of items){try{const data=await open(item);const checkpoint=async()=>offlineStore.pending.update(item.id,await seal(item.ownerId,data));
if(!data.patientSaved){await post('/api/patients',{clientRequestId:data.patientId,...(data.patientName?{name:data.patientName}:{}),age:data.age,language:data.language,consent:data.consent,consentAuthority:data.age<18?'guardian':'self'});data.patientSaved=true;await checkpoint();}
if(!data.encounterSaved){await post('/api/encounters',{clientRequestId:data.encounterId,patientId:data.patientId,text:data.text,language:data.language,inputType:data.inputType});data.encounterSaved=true;await checkpoint();}
if(data.audioMedia&&!data.audioSaved){await upload('/api/speech/upload',data,data.audioMedia,'audioId',data.audioId);data.audioSaved=true;await checkpoint();}
for(const document of data.documents??[]){if(!document.saved){await upload('/api/reports/upload',data,document.media,'reportId',document.id);document.saved=true;await checkpoint();}}
if(!data.reportSaved){if(data.reportMedia)await upload('/api/reports/upload',data,data.reportMedia,'reportId',data.reportId);else if(data.report.trim())await post('/api/reports/ocr',{encounterId:data.encounterId,rawText:data.report,clientRequestId:data.reportId});data.reportSaved=true;await checkpoint();}
const response=await fetch('/api/encounters/'+data.encounterId,{cache:'no-store'});const stored=await response.json();if(!stored.ok)throw new Error(stored.error.code);
const reviewed=['TRIAGED','IN_REVIEW','INFO_REQUESTED','APPROVED','ESCALATED','REFERRAL_GENERATED','COMPLETED'].includes(stored.data.encounter.state);
const verificationRequired=Boolean(data.reportMedia||data.documents?.length)&&!reviewed;
if(!data.reportMedia&&!data.documents?.length&&!reviewed){if(stored.data.encounter.state==='PROCESSING')throw new Error('PROCESSING');await post('/api/triage/analyze',{encounterId:data.encounterId});}
await offlineStore.pending.delete(item.id);synced++;window.dispatchEvent(new CustomEvent<SyncedIntake>('sf-intake-synced',{detail:{draftId:item.id,encounterId:data.encounterId,verificationRequired}}));}catch(error){await offlineStore.pending.update(item.id,{status:'SYNC_FAILED',error:error instanceof Error?error.message:'SYNC_FAILED'});failed++;}}
window.dispatchEvent(new Event('sf-offline-change'));return {synced,failed};};
return navigator.locks?navigator.locks.request('swasthyaflow-sync',run):{synced:0,failed:1,error:'SYNC_LOCK_UNAVAILABLE'};}

export async function clearPrivateDrafts(){invalidateOfflineActor();await offlineStore.pending.clear();await offlineStore.keys.clear();localStorage.removeItem('sf_simulate_offline');}
