import {deliveryLabels} from './referral-delivery-config';
import {z} from 'zod';
export const referralConsentVersion='1.0-IN';
export const recipientSchema=z.object({receivingFacilityId:z.string().max(100).optional(),name:z.string().trim().min(3).max(160),kind:z.enum(['government_hospital','psu_hospital','specialist']),institution:z.string().trim().min(3).max(160),department:z.string().trim().min(2).max(100),registrationNumber:z.string().trim().max(100).default(''),verificationReference:z.string().trim().min(10).max(500),verified:z.literal(true)}).strict().superRefine((v,ctx)=>{if(v.kind==='specialist'&&!v.registrationNumber)ctx.addIssue({code:'custom',path:['registrationNumber'],message:'Specialist registration number required.'});});
export const referralSchema=z.object({encounterId:z.string().uuid(),recipientId:z.string().uuid(),reason:z.string().trim().min(10).max(1000),consentConfirmed:z.literal(true),consentAuthority:z.enum(['self','guardian']),includeName:z.boolean().default(false)}).strict();
export type ReferralReport={version:1;recipient:{name:string;kind:string;institution:string;department:string;registrationNumber:string};patient:{reference:string;name:string|null;age:number;language:string};sourceFacility:string;doctor:string;createdAt:string;reason:string;summary:string;priority:string;consentAuthority:string;consentVersion:string;deliveryStatus:'NOT_SENT'};
export function escapeHtml(text:string){return text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function referralHtml(r:ReferralReport,id:string,deliveryStatus=r.deliveryStatus as string){const e=escapeHtml;const row=(label:string,value:string)=>`<h2>${e(label)}</h2><p>${e(value)}</p>`;return `<!doctype html><html lang="${e(r.patient.language)}"><meta charset="utf-8"><title>Confidential referral</title><style>@page{size:A4;margin:20mm}body{font:14px Arial,"Nirmala UI",sans-serif;color:#17231e;line-height:1.6}h1{font-size:26px}h2{font-size:13px;color:#245c4d;margin:22px 0 4px}p{white-space:pre-wrap;overflow-wrap:anywhere;margin:0}.notice{border:1px solid #a5b8b0;padding:12px;margin:20px 0}footer{margin-top:32px;font-size:11px}</style><body><h1>SwasthyaFlow · Referral report</h1><p>Confidential · Recipient-specific · ${e((deliveryLabels[deliveryStatus]??deliveryStatus).toUpperCase())}</p>${row('Reference',id)}${row('Recipient',`${r.recipient.name}\n${r.recipient.institution} · ${r.recipient.department}${r.recipient.registrationNumber?'\nRegistration: '+r.recipient.registrationNumber:''}`)}${row('Patient',`${r.patient.reference}${r.patient.name?' · '+r.patient.name:''}\nAge: ${r.patient.age} · Language: ${r.patient.language}`)}${row('Referring facility / approving doctor',`${r.sourceFacility}\n${r.doctor} · ${r.createdAt}`)}${row('Referral purpose',r.reason)}${row('Doctor-reviewed concerns',r.summary)}${row('Review priority',r.priority)}<div class="notice">This report records source-based concerns for qualified staff review. It provides no diagnosis, treatment advice or prescription. Review priority does not determine treatment. Original documents appear in an appendix only after explicit document-sharing consent. Audio is excluded.</div><footer>Separate recipient-specific consent recorded (${e(r.consentAuthority)}; ${e(r.consentVersion)}). PDF generation or printing alone does not transmit this report. Delivery status records software receipt only, not clinical acceptance or an appointment. Share only through the facility's approved confidential handover process. Do not publish or redistribute.</footer></body></html>`;}




