export type EncounterState = 'DRAFT'|'CONSENTED'|'INPUT_CAPTURED'|'PROCESSING'|'TRIAGED'|'IN_REVIEW'|'INFO_REQUESTED'|'APPROVED'|'ESCALATED'|'REFERRAL_GENERATED'|'COMPLETED'|'ASR_FAILED'|'OCR_FAILED'|'AI_FAILED'|'AI_PARSE_FAILED'|'TRIAGE_FAILED'|'SAFETY_ENGINE_FAILED'|'SAVE_FAILED'|'PENDING_SYNC';
const legal:Partial<Record<EncounterState,EncounterState[]>>={
 DRAFT:['CONSENTED'], CONSENTED:['INPUT_CAPTURED'], INPUT_CAPTURED:['PROCESSING','PENDING_SYNC'],
 PROCESSING:['TRIAGED','ASR_FAILED','OCR_FAILED','AI_FAILED','AI_PARSE_FAILED','TRIAGE_FAILED','SAFETY_ENGINE_FAILED','SAVE_FAILED'],
 TRIAGED:['IN_REVIEW','PROCESSING'], IN_REVIEW:['INFO_REQUESTED','APPROVED','ESCALATED','PROCESSING'],
 INFO_REQUESTED:['INPUT_CAPTURED','PROCESSING'], APPROVED:['REFERRAL_GENERATED','COMPLETED'], ESCALATED:['REFERRAL_GENERATED','COMPLETED'],
 REFERRAL_GENERATED:['COMPLETED'], ASR_FAILED:['PROCESSING','IN_REVIEW'], OCR_FAILED:['PROCESSING','IN_REVIEW'], AI_FAILED:['PROCESSING','IN_REVIEW'], AI_PARSE_FAILED:['PROCESSING','IN_REVIEW'], TRIAGE_FAILED:['PROCESSING','IN_REVIEW'], SAFETY_ENGINE_FAILED:['PROCESSING','IN_REVIEW'], SAVE_FAILED:['PROCESSING','IN_REVIEW'], PENDING_SYNC:['INPUT_CAPTURED']
};
export function transition(from:EncounterState,to:EncounterState,consent:boolean,reviewed:boolean):EncounterState {
 if (!legal[from]?.includes(to)) throw new Error('ILLEGAL_TRANSITION');
 if (to==='PROCESSING'&&!consent) throw new Error('CONSENT_REQUIRED');
 if (to==='COMPLETED'&&!reviewed) throw new Error('REVIEW_REQUIRED');
 return to;
}
