import {clinicalReviewerSession} from '@/lib/reviewer-auth';
import {z} from 'zod';
import {and,eq} from 'drizzle-orm';
import {session} from '@/lib/auth';
import {db} from '@/lib/db/server';
import {referralRecipients,auditLogs,facilities} from '@/db/schema';
import {failure,success,parseFailure} from '@/lib/api';
import {recipientSchema} from '@/lib/referral-policy';
export async function GET(){const actor=await clinicalReviewerSession();if(!actor?.facilityId||!['administrator','medical_officer'].includes(actor.role))return failure('FORBIDDEN','Doctor or administrator role required.',403);const rows=await (await db()).select().from(referralRecipients).where(eq(referralRecipients.facilityId,actor.facilityId));return success(rows);}
export async function POST(req:Request){const actor=await session();if(actor?.role!=='administrator'||!actor.facilityId)return failure('FORBIDDEN','Administrator role required.',403);try{const data=recipientSchema.parse(await req.json());const conn=await db();const id=crypto.randomUUID();if(data.receivingFacilityId){const [facility]=await conn.select({id:facilities.id}).from(facilities).where(eq(facilities.id,data.receivingFacilityId)).limit(1);if(!facility)return failure("INVALID_WORKSPACE","Receiving workspace not found.",422);}await conn.transaction(async tx=>{await tx.insert(referralRecipients).values({id,facilityId:actor.facilityId!,receivingFacilityId:data.receivingFacilityId||null,name:data.name,kind:data.kind,institution:data.institution,department:data.department,registrationNumber:data.registrationNumber,verificationReference:data.verificationReference,verifiedBy:actor.id});await tx.insert(auditLogs).values({id:crypto.randomUUID(),userId:actor.id,facilityId:actor.facilityId,action:'REFERRAL_RECIPIENT_VERIFIED',metadata:{recipientId:id}});});return success({id},201);}catch(e){return parseFailure(e);}}
export async function PATCH(req:Request){const actor=await session();if(actor?.role!=='administrator'||!actor.facilityId)return failure('FORBIDDEN','Administrator role required.',403);try{const data=z.object({id:z.string().uuid(),active:z.boolean()}).strict().parse(await req.json());const conn=await db();const changed=await conn.transaction(async tx=>{const rows=await tx.update(referralRecipients).set({active:data.active}).where(and(eq(referralRecipients.id,data.id),eq(referralRecipients.facilityId,actor.facilityId!))).returning({id:referralRecipients.id});if(rows.length)await tx.insert(auditLogs).values({id:crypto.randomUUID(),userId:actor.id,facilityId:actor.facilityId,action:'REFERRAL_RECIPIENT_STATUS_CHANGED',metadata:{recipientId:data.id,active:data.active}});return rows.length;});return changed?success({updated:true}):failure('NOT_FOUND','Recipient not found.',404);}catch(e){return parseFailure(e);}}


