import { pgTable, text, integer, timestamp, jsonb, boolean } from 'drizzle-orm/pg-core';

const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
export const facilities = pgTable('facilities', { id:text('id').primaryKey(), name:text('name').notNull(), type:text('type').notNull(), location:text('location').notNull(), createdAt:created() });
export const users = pgTable('users', { id:text('id').primaryKey(), name:text('name').notNull(), role:text('role').notNull(), facilityId:text('facility_id').references(()=>facilities.id), createdAt:created() });
export const patients = pgTable('patients', { id:text('id').primaryKey(), anonymousPatientId:text('anonymous_patient_id').notNull().unique(), age:integer('age').notNull(), sex:text('sex'), preferredLanguage:text('preferred_language').notNull(), consentStatus:boolean('consent_status').notNull().default(false), createdAt:created() });
export const encounters = pgTable('encounters', { id:text('id').primaryKey(), patientId:text('patient_id').notNull().references(()=>patients.id), chiefComplaint:text('chief_complaint').notNull().default(''), symptoms:jsonb('symptoms').$type<string[]>().notNull().default([]), timeline:jsonb('timeline').$type<string[]>().notNull().default([]), priority:text('priority'), priorityFinal:text('priority_final'), prioritySource:text('priority_source'), status:text('status').notNull().default('DRAFT'), state:text('state').notNull().default('DRAFT'), facilityId:text('facility_id').references(()=>facilities.id), createdAt:created() });
export const inputs = pgTable('inputs', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), type:text('type').notNull(), originalText:text('original_text'), transcript:text('transcript'), language:text('language'), source:jsonb('source').$type<Record<string,unknown>>(), createdAt:created() });
export const reports = pgTable('reports', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), fileUrl:text('file_url'), rawOcr:text('raw_ocr'), extractedData:jsonb('extracted_data').$type<Record<string,unknown>>(), qualityStatus:text('quality_status'), ocrTokens:jsonb('ocr_tokens').$type<unknown[]>(), createdAt:created() });
export const triageNotes = pgTable('triage_notes', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), summary:text('summary').notNull(), missingInformation:jsonb('missing_information').$type<string[]>().notNull().default([]), followUpQuestions:jsonb('follow_up_questions').$type<string[]>().notNull().default([]), riskSignals:jsonb('risk_signals').$type<unknown[]>().notNull().default([]), priority:text('priority').notNull(), fieldSources:jsonb('field_sources').$type<Record<string,unknown>>().notNull().default({}), createdAt:created() });
export const reviews = pgTable('reviews', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), reviewerId:text('reviewer_id').notNull().references(()=>users.id), changes:jsonb('changes').$type<Record<string,unknown>>().notNull().default({}), decision:text('decision').notNull(), notes:text('notes'), createdAt:created() });
export const referrals = pgTable('referrals', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), content:text('content').notNull(), createdAt:created() });
export const auditLogs = pgTable('audit_logs', { id:text('id').primaryKey(), userId:text('user_id'), encounterId:text('encounter_id'), action:text('action').notNull(), timestamp:timestamp('timestamp',{withTimezone:true}).notNull().defaultNow(), metadata:jsonb('metadata').$type<Record<string,unknown>>().notNull().default({}) });
export const rulesConfig = pgTable('rules_config', { id:text('id').primaryKey(), version:integer('version').notNull(), rules:jsonb('rules').$type<unknown[]>().notNull(), active:boolean('active').notNull().default(false), createdAt:created() });
