export type ReferralAttachment={id:string;name:string;mime:string;sha256:string;documentType:string};
import { pgTable, text, integer, timestamp, jsonb, boolean, index } from 'drizzle-orm/pg-core';

const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
export const referralDeliveries=pgTable('referral_deliveries',{id:text('id').primaryKey().references(()=>referrals.id,{onDelete:'cascade'}),facilityId:text('facility_id').notNull().references(()=>facilities.id),recipientId:text('recipient_id').notNull().references(()=>referralRecipients.id),receivingFacilityId:text('receiving_facility_id').references(()=>facilities.id),attachments:jsonb('attachments').$type<ReferralAttachment[]>().notNull().default([]),decision:text('decision'),decidedBy:text('decided_by').references(()=>users.id),decidedAt:timestamp('decided_at',{withTimezone:true}),requestedBy:text('requested_by').notNull().references(()=>users.id),consentAt:timestamp('consent_at',{withTimezone:true}).notNull(),connectorFingerprint:text('connector_fingerprint').notNull(),mode:text('mode').notNull(),state:text('state').notNull().default('QUEUED'),attempts:integer('attempts').notNull().default(0),nextAttemptAt:timestamp('next_attempt_at',{withTimezone:true}).notNull().defaultNow(),leaseUntil:timestamp('lease_until',{withTimezone:true}),leaseId:text('lease_id'),receiptId:text('receipt_id'),receivedAt:timestamp('received_at',{withTimezone:true}),errorCode:text('error_code'),createdAt:created()},t=>[index('referral_delivery_due_idx').on(t.state,t.nextAttemptAt),index('referral_delivery_facility_idx').on(t.facilityId,t.createdAt)]);
export const facilities = pgTable('facilities', { id:text('id').primaryKey(), name:text('name').notNull(), type:text('type').notNull(), location:text('location').notNull(), settings:jsonb('settings').$type<Record<string,unknown>>().notNull().default({}), createdAt:created() });
export const users = pgTable('users', { id:text('id').primaryKey(), name:text('name').notNull(), username:text('username').unique(), passwordHash:text('password_hash'), role:text('role').notNull(), active:boolean('active').notNull().default(true), facilityId:text('facility_id').references(()=>facilities.id), lastLoginAt:timestamp('last_login_at',{withTimezone:true}), createdAt:created() });
export const patientIdCounters = pgTable('patient_id_counters', { id:text('id').primaryKey(), nextValue:integer('next_value').notNull().default(1001) });
export const patients = pgTable('patients', { id:text('id').primaryKey(), anonymousPatientId:text('anonymous_patient_id').notNull().unique(), name:text('name'), age:integer('age').notNull(), sex:text('sex'), preferredLanguage:text('preferred_language').notNull(), consentStatus:boolean('consent_status').notNull().default(false), facilityId:text('facility_id').notNull().references(()=>facilities.id), createdAt:created() });
export const encounters = pgTable('encounters', { id:text('id').primaryKey(), patientId:text('patient_id').notNull().references(()=>patients.id), chiefComplaint:text('chief_complaint').notNull().default(''), symptoms:jsonb('symptoms').$type<string[]>().notNull().default([]), timeline:jsonb('timeline').$type<string[]>().notNull().default([]), priority:text('priority'), priorityFinal:text('priority_final'), prioritySource:text('priority_source'), status:text('status').notNull().default('DRAFT'), state:text('state').notNull().default('DRAFT'), facilityId:text('facility_id').references(()=>facilities.id), createdAt:created() });
export const inputs = pgTable('inputs', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), type:text('type').notNull(), originalText:text('original_text'), transcript:text('transcript'), language:text('language'), source:jsonb('source').$type<Record<string,unknown>>(), createdAt:created() });
export const reports = pgTable('reports', { id:text('id').primaryKey(), documentType:text('document_type').notNull().default('report'), encounterId:text('encounter_id').notNull().references(()=>encounters.id), fileUrl:text('file_url'), fileName:text('file_name'), fileMimeType:text('file_mime_type'), fileSize:integer('file_size'), fileSha256:text('file_sha256'), pageCount:integer('page_count'), qualityWarnings:jsonb('quality_warnings').$type<string[]>().notNull().default([]), rawOcr:text('raw_ocr'), reviewedText:text('reviewed_text'), reviewedBy:text('reviewed_by').references(()=>users.id), reviewedAt:timestamp('reviewed_at',{withTimezone:true}), extractedData:jsonb('extracted_data').$type<Record<string,unknown>>(), qualityStatus:text('quality_status'), ocrTokens:jsonb('ocr_tokens').$type<unknown[]>(), ocrEngine:text('ocr_engine'), ocrConfidencePermille:integer('ocr_confidence_permille'), ocrCompletedAt:timestamp('ocr_completed_at',{withTimezone:true}), ocrError:text('ocr_error'), createdAt:created() });
export const triageNotes = pgTable('triage_notes', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), summary:text('summary').notNull(), missingInformation:jsonb('missing_information').$type<string[]>().notNull().default([]), followUpQuestions:jsonb('follow_up_questions').$type<string[]>().notNull().default([]), riskSignals:jsonb('risk_signals').$type<unknown[]>().notNull().default([]), priority:text('priority').notNull(), fieldSources:jsonb('field_sources').$type<Record<string,unknown>>().notNull().default({}), createdAt:created() });
export const reviews = pgTable('reviews', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), reviewerId:text('reviewer_id').notNull().references(()=>users.id), changes:jsonb('changes').$type<Record<string,unknown>>().notNull().default({}), decision:text('decision').notNull(), notes:text('notes'), createdAt:created() });
export const referralRecipients=pgTable('referral_recipients',{receivingFacilityId:text('receiving_facility_id').references(()=>facilities.id),id:text('id').primaryKey(),facilityId:text('facility_id').notNull().references(()=>facilities.id),name:text('name').notNull(),kind:text('kind').notNull(),institution:text('institution').notNull(),department:text('department').notNull(),registrationNumber:text('registration_number').notNull().default(''),verificationReference:text('verification_reference').notNull(),verifiedBy:text('verified_by').notNull().references(()=>users.id),active:boolean('active').notNull().default(true),createdAt:created()});
export const referrals = pgTable('referrals', { id:text('id').primaryKey(), encounterId:text('encounter_id').notNull().references(()=>encounters.id), content:text('content').notNull(),recipientId:text('recipient_id').references(()=>referralRecipients.id),approvedBy:text('approved_by').references(()=>users.id),consentAt:timestamp('consent_at',{withTimezone:true}),deliveryStatus:text('delivery_status').notNull().default('NOT_SENT'),createdAt:created() });
export const auditLogs = pgTable('audit_logs', { id:text('id').primaryKey(), userId:text('user_id'), encounterId:text('encounter_id'), facilityId:text('facility_id').references(()=>facilities.id), action:text('action').notNull(), timestamp:timestamp('timestamp',{withTimezone:true}).notNull().defaultNow(), metadata:jsonb('metadata').$type<Record<string,unknown>>().notNull().default({}) },table=>[index('audit_logs_facility_timestamp_idx').on(table.facilityId,table.timestamp)]);
export const rulesConfig = pgTable('rules_config', { id:text('id').primaryKey(), facilityId:text('facility_id').notNull().references(()=>facilities.id), version:integer('version').notNull(), rules:jsonb('rules').$type<unknown[]>().notNull(), status:text('status').notNull().default('DRAFT'), active:boolean('active').notNull().default(false), checksum:text('checksum'), createdBy:text('created_by').references(()=>users.id), approvedBy:text('approved_by').references(()=>users.id), approvedAt:timestamp('approved_at',{withTimezone:true}), createdAt:created() });
export const rateLimitEvents = pgTable('rate_limit_events',{id:text('id').primaryKey(),key:text('key').notNull(),createdAt:created()},table=>[index('rate_limit_events_key_created_idx').on(table.key,table.createdAt)]);
export const processingMetrics=pgTable('processing_metrics',{id:text('id').primaryKey(),facilityId:text('facility_id').notNull().references(()=>facilities.id),stage:text('stage').notNull(),durationMs:integer('duration_ms').notNull(),succeeded:boolean('succeeded').notNull(),createdAt:created()},table=>[index('processing_metrics_facility_created_idx').on(table.facilityId,table.createdAt)]);

