import {z} from 'zod';
import {providerMode} from '../provider-mode';
import {providerFixtures} from '../provider-fixtures';
export type Translation={original:string;normalized:string;ambiguousSpans:{original:string;normalized:string;reason:string}[]};
export interface TranslationAdapter{normalize(text:string,srcLang:'en'|'hi'|'or'):Promise<Translation>}
export const fixtureTranslation:TranslationAdapter={async normalize(text,srcLang){if(srcLang==='en')return {original:text,normalized:text,ambiguousSpans:[]};const fixture=(await providerFixtures()).translation.find(item=>item.original===text&&item.language===srcLang);if(!fixture)throw new Error('FIXTURE_INPUT_NOT_REGISTERED');return {original:text,normalized:fixture.normalized,ambiguousSpans:fixture.ambiguousSpans};}};
const phrases:[RegExp,string][]=[[/बुखार|ଜ୍ୱର/i,'fever'],[/बेहोश|ଅଚେତ/i,'fainting'],[/तेज दर्द|ତୀବ୍ର ଯନ୍ତ୍ରଣା/i,'severe pain'],[/सांस फूल|ଶ୍ୱାସକଷ୍ଟ/i,'breathlessness'],[/ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ|सांस लेने में कठिनाई/i,'difficulty breathing']];
export const localTranslation:TranslationAdapter={async normalize(text,srcLang){if(srcLang==='en')return {original:text,normalized:text,ambiguousSpans:[]};const normalized=phrases.filter(([pattern])=>pattern.test(text)).map(([,value])=>value).join(', ');return {original:text,normalized:normalized||text,ambiguousSpans:normalized?[]:[{original:text,normalized:text,reason:'No controlled translation match; original retained'}]};}};
const liveSchema=z.object({normalized:z.string(),ambiguousSpans:z.array(z.object({original:z.string(),normalized:z.string(),reason:z.string()})).default([])});
export const liveTranslation:TranslationAdapter={async normalize(text,srcLang){if(srcLang==='en')return {original:text,normalized:text,ambiguousSpans:[]};if(!process.env.TRANSLATION_API_URL||!process.env.TRANSLATION_API_KEY)throw new Error('TRANSLATION_FAILED');let response:Response;try{response=await fetch(process.env.TRANSLATION_API_URL,{method:'POST',headers:{authorization:`Bearer ${process.env.TRANSLATION_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({text,source_language:srcLang,target_language:'en',model:'IndicTrans2'}),signal:AbortSignal.timeout(15_000),cache:'no-store'});}catch{throw new Error('TRANSLATION_FAILED');}if(!response.ok)throw new Error('TRANSLATION_FAILED');const parsed=liveSchema.safeParse(await response.json());if(!parsed.success)throw new Error('TRANSLATION_FAILED');return {original:text,...parsed.data};}};
export function translationAdapter():TranslationAdapter{const mode=providerMode('TRANSLATION_MODE',process.env.AI_MODE||'local',['fixture','local','live','enterprise']);return mode==='fixture'?fixtureTranslation:mode==='live'||mode==='enterprise'?liveTranslation:localTranslation;}
