import {z} from 'zod';
export type Segment={text:string;confidence:number;start?:number;end?:number};
export type Transcript={text:string;language:string;segments:Segment[]};
export interface SpeechAdapter{transcribe(audio:Blob,langHint:'en'|'hi'|'or'):Promise<Transcript>}
const examples={en:'I have had fever for four days.',hi:'मुझे चार दिन से बुखार है।',or:'ମୋତେ ନିଶ୍ୱାସ ନେବାରେ କଷ୍ଟ ହେଉଛି।'};
export const mockSpeech:SpeechAdapter={async transcribe(_audio,langHint){await new Promise(resolve=>setTimeout(resolve,800));const text=examples[langHint];return {text,language:langHint,segments:[{text,confidence:langHint==='or'?0.65:0.88,start:0,end:4}]};}};
const whisperSchema=z.object({text:z.string(),language:z.string().optional(),segments:z.array(z.object({text:z.string(),start:z.number(),end:z.number(),avg_logprob:z.number().optional()})).optional()});
export const liveSpeech:SpeechAdapter={async transcribe(audio,langHint){if(!process.env.SPEECH_TO_TEXT_API_KEY)throw new Error('ASR_FAILED');const form=new FormData();form.set('file',new File([audio],'speech.webm',{type:audio.type||'audio/webm'}));form.set('model','whisper-1');form.set('response_format','verbose_json');form.set('language',langHint==='or'?'or':langHint);const response=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{authorization:`Bearer ${process.env.SPEECH_TO_TEXT_API_KEY}`},body:form});if(!response.ok)throw new Error('ASR_FAILED');const parsed=whisperSchema.safeParse(await response.json());if(!parsed.success||!parsed.data.text.trim())throw new Error('ASR_FAILED');return {text:parsed.data.text,language:parsed.data.language??langHint,segments:parsed.data.segments?.map(s=>({text:s.text,start:s.start,end:s.end,confidence:s.avg_logprob===undefined?0.5:Math.max(0,Math.min(1,Math.exp(s.avg_logprob)))}))??[{text:parsed.data.text,confidence:0.5}]};}};
export function speechAdapter():SpeechAdapter{return process.env.AI_MODE==='live'?liveSpeech:mockSpeech;}
