import {z} from 'zod';
import {providerMode} from '../provider-mode';
import {providerFixtures,sourceHash} from '../provider-fixtures';
export type Segment={text:string;confidence:number;start?:number;end?:number};
export type Transcript={text:string;language:string;segments:Segment[]};
export interface SpeechAdapter{transcribe(audio:Blob,langHint:'en'|'hi'|'or'):Promise<Transcript>}
const unavailableSpeech:SpeechAdapter={async transcribe(){throw new Error('ASR_NOT_CONFIGURED');}};
export const fixtureSpeech:SpeechAdapter={async transcribe(audio,langHint){const digest=sourceHash(new Uint8Array(await audio.arrayBuffer()));const fixture=(await providerFixtures()).speech.find(item=>item.sha256===digest&&item.language===langHint);if(!fixture)throw new Error('FIXTURE_INPUT_NOT_REGISTERED');return {text:fixture.text,language:fixture.language,segments:fixture.segments};}};
const whisperSchema=z.object({text:z.string(),language:z.string().optional(),segments:z.array(z.object({text:z.string(),start:z.number(),end:z.number(),avg_logprob:z.number().optional()})).optional()});
export const liveSpeech:SpeechAdapter={async transcribe(audio,langHint){if(!process.env.SPEECH_TO_TEXT_API_KEY||!process.env.SPEECH_TO_TEXT_API_URL||!process.env.SPEECH_TO_TEXT_MODEL)throw new Error('ASR_NOT_CONFIGURED');const form=new FormData();form.set('file',new File([audio],'speech.webm',{type:audio.type||'audio/webm'}));form.set('model',process.env.SPEECH_TO_TEXT_MODEL);form.set('response_format','verbose_json');form.set('language',langHint==='or'?'or':langHint);let response:Response;try{response=await fetch(process.env.SPEECH_TO_TEXT_API_URL,{method:'POST',headers:{authorization:`Bearer ${process.env.SPEECH_TO_TEXT_API_KEY}`},body:form,signal:AbortSignal.timeout(15_000)});}catch{throw new Error('ASR_FAILED');}if(!response.ok)throw new Error('ASR_FAILED');const parsed=whisperSchema.safeParse(await response.json());if(!parsed.success||!parsed.data.text.trim())throw new Error('ASR_FAILED');return {text:parsed.data.text,language:parsed.data.language??langHint,segments:parsed.data.segments?.map(s=>({text:s.text,start:s.start,end:s.end,confidence:s.avg_logprob===undefined?0.5:Math.max(0,Math.min(1,Math.exp(s.avg_logprob)))}))??[{text:parsed.data.text,confidence:0.5}]};}};
export function speechAdapter():SpeechAdapter{const mode=providerMode('ASR_MODE',process.env.AI_MODE==='enterprise'?'enterprise':process.env.AI_MODE==='live'?'live':'unavailable',['fixture','live','enterprise','unavailable']);return mode==='fixture'?fixtureSpeech:mode==='live'||mode==='enterprise'?liveSpeech:unavailableSpeech;}
