import {z} from 'zod';
import {and,eq,sql} from 'drizzle-orm';
import {db} from '@/lib/db/server';
import {encounters,patients,inputs,reports,triageNotes,reviews,referrals,auditLogs} from '@/db/schema';
import {session} from '@/lib/auth';
import {failure,success,parseFailure} from '@/lib/api';
import {objectStorage,reportStorageKey} from '@/lib/storage';
const schema=z.object({encounterId:z.string().min(1)}).strict();
export async function POST(req:Request){const actor=await session();if(actor?.role!=='administrator'||!actor.facilityId)return failure('FORBIDDEN','Administrator role required.',403);try{const {encounterId}=schema.parse(await req.json());const conn=await db();const [encounter]=await conn.select({id:encounters.id,patientId:encounters.patientId}).from(encounters).where(and(eq(encounters.id,encounterId),eq(encounters.facilityId,actor.facilityId))).limit(1);if(!encounter)return failure('NOT_FOUND','Encounter not found.',404);const [allReports,allInputs]=await Promise.all([conn.select({fileUrl:reports.fileUrl}).from(reports).where(eq(reports.encounterId,encounterId)),conn.select({audioId:sql<string>`${inputs.source}->>'audioId'`}).from(inputs).where(eq(inputs.encounterId,encounterId))]);await conn.transaction(async tx=>{await tx.delete(referrals).where(eq(referrals.encounterId,encounterId));await tx.delete(reviews).where(eq(reviews.encounterId,encounterId));await tx.delete(triageNotes).where(eq(triageNotes.encounterId,encounterId));await tx.delete(reports).where(eq(reports.encounterId,encounterId));await tx.delete(inputs).where(eq(inputs.encounterId,encounterId));await tx.delete(encounters).where(eq(encounters.id,encounterId));const other=await tx.select({id:encounters.id}).from(encounters).where(eq(encounters.patientId,encounter.patientId)).limit(1);if(!other.length)await tx.delete(patients).where(eq(patients.id,encounter.patientId));await tx.insert(auditLogs).values({id:crypto.randomUUID(),userId:actor.id,encounterId,facilityId:actor.facilityId,action:'ENCOUNTER_PURGED',metadata:{clinical_data_removed:true}});});let fileErrors=0;for(const report of allReports){if(report.fileUrl&&/^(reports\/)?[0-9a-f-]+\.(png|jpg|pdf)$/.test(report.fileUrl))try{await objectStorage().delete(reportStorageKey(report.fileUrl));}catch{fileErrors++;}}for(const input of allInputs){const audioId=input.audioId;if(typeof audioId==='string'&&/^[0-9a-f-]{36}$/.test(audioId))try{await objectStorage().delete(`audio/${audioId}.webm`);}catch{fileErrors++;}}if(fileErrors)return failure('PURGE_FILE_FAILED','Database data was removed but file cleanup needs administrator attention.',500);return success({purged:true});}catch(e){return parseFailure(e);}}
